using System;
using NHSD.GPIT.BuyingCatalogue.PlaywrightTests.TestData.Generators;

namespace NHSD.GPIT.BuyingCatalogue.PlaywrightTests.TestData;

public class AdminTestData
{
    public string BaseUrl { get; set; } = "https://localhost:5001";

    public string Email { get; set; } = "bobsmith@email.com";
    public string Password { get; set; } = "Pass123$";

    // User creation
    public string Organisation = "NHS HUMBER AND NORTH YORKSHIRE INTEGRATED CARE BOARD";
    public string AccountType = "Buyer";
    public string AccountStatus = "Active";
    public string FirstName = TestDataGenerator.FirstName();
    public string LastName = TestDataGenerator.LastName();

    public string UserEmail =
        $"{TestDataGenerator.FirstName().ToLower()}.{TestDataGenerator.LastName().ToLower()}.{Guid.NewGuid().ToString("N")[..6]}@nhs.net";

    // Email domains
    public string EmailDomain =
        $"@test{DateTime.UtcNow:HHmmssfff}.net";

    // Contracting vehicles
    public string ContractingVehicleName = $"Test contracting vehicle {DateTime.UtcNow:HHmmssfff}";
    public string ContractingVehicleDuration = "18";

    // Supplier defined Epic
    public string EpicName = $"Test Epic {DateTime.UtcNow:HHmmssfff}";
    public string EpicDescription = "Test Epic description generated by automated test";
    public string EpicCapability = "Appointments Management - GP";

    // Interoperability
    public string IntegrationTypeName = $"{DateTime.UtcNow:HHmmssfff}";
    public string IntegrationTypeDescription = "Test integration type description";

    // Supplier
    public string SupplierName = $"Test Supplier {DateTime.UtcNow:HHmmssfff}";
    public string SupplierLegalName = $"Test Supplier Legal {DateTime.UtcNow:HHmmssfff}";
    public string SupplierAbout = "Test supplier description generated by automated test";
    public string SupplierAddressLine1 = TestDataGenerator.StreetAddress();
    public string SupplierAddressLine2 = TestDataGenerator.SecondaryAddress();
    public string SupplierAddressLine3 = TestDataGenerator.County();
    public string SupplierTown = TestDataGenerator.City();
    public string SupplierPostcode = "LS1 1BT";
    public string SupplierCountry = "United Kingdom";
    public string SupplierContactFirstName = TestDataGenerator.FirstName();
    public string SupplierContactLastName = TestDataGenerator.LastName();
    public string SupplierContactDepartment = "NHS";
    public string SupplierContactPhone = TestDataGenerator.PhoneNumber();
    public string SupplierContactEmail = TestDataGenerator.Email();

    // Capabilities and Epics upload
    public string CapabilitiesFile = "CapabilitiesAndSolutions.csv";
    public string EpicsFile = "EpicsAndSolutions.csv";

    // Catalogue solution
    public string SolutionName = $"Test Solution {DateTime.UtcNow:HHmmssfff}";
    public string SolutionSummary = "Test solution summary generated by automated test";
    public string SolutionFullDescription = "Test solution full description generated by automated test";
    public string SolutionFeature1 = "Automated test feature one";
    public string SolutionFeature2 = "Automated test feature two";
    public string HostingSummary = "Test hosting summary";
    public string HostingDataCentreModel = "Test data centre model";
    public string StorageSpace = "Test storage space";
    public string ProcessingPower = "Test processing power";
    public string SlaSupportType = "Automated test support";
    public string SlaServiceType = "Automated test service";
    public string SlaServiceLevel = "Automated test service level";
    public string SlaHowMeasured = "Automated test measurement approach";
}
