variables:
  - name: buildConfiguration
    value: Release
  - name: dotnetVersion
    value: '7.0.203'

trigger:
  branches:
    include:
      - develop
  paths:
    exclude:
      - "src/**"
      - "terraform/**"
      - "tests/**"
    include:
      - "src/BuyingCatalogueFunction*"
      - "terraform/functionapp"
      - "tests/BuyingCatalogueFunctionTests"

pool:
  vmImage: ubuntu-latest

jobs:
  - job: build
    displayName: Build and Test
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: DotNetCoreCLI@2
        displayName: Build solution
        inputs:
          command: "build"
          projects: "NHSD.GPIT.OrganisationImport.sln"
          arguments: "--configuration $(buildConfiguration)"

      - task: DotNetCoreCLI@2
        displayName: Run tests
        inputs:
          command: "test"
          projects: "NHSD.GPIT.OrganisationImport.sln"
          arguments: "--no-build --configuration $(buildConfiguration) -- xunit.parallelizeTestCollections=true"

      - task: DotNetCoreCLI@2
        displayName: Publish BuyingCatalogueFunction
        inputs:
          command: "publish"
          projects: "src/BuyingCatalogueFunction"
          arguments: "--no-build --configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/BuyingCatalogueFunction"
          publishWebProjects: false
          modifyOutputPath: false
          zipAfterPublish: true

      - task: PublishBuildArtifacts@1
        displayName: Package BuyingCatalogueFunction
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)/BuyingCatalogueFunction"
          ArtifactName: "BuyingCatalogueFunction"
          publishLocation: "Container"

  - job: Terraform
    displayName: Package Terraform
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: CopyFiles@2
        displayName: Copy Function App TF Files
        inputs:
          SourceFolder: "terraform/functionapp"
          Contents: "**"
          TargetFolder: "$(build.artifactStagingDirectory)/terraform/functionapp"
          CleanTargetFolder: false
          OverWrite: true

      - publish: $(build.artifactStagingDirectory)/terraform/functionapp
        artifact: terraform-functionapp
