variables:
  - name: buildConfiguration
    value: Release

trigger:
  branches:
    include:
      - develop
  paths:
    exclude:
      - "src/**"
      - "terraform/**"
      - "tests/**"
    include:
      - "src/OrganisationImporter*"
      - "terraform/orgimport"
      - "OrganisationImporter/OrganisationImporterTests"

pool:
  vmImage: ubuntu-latest

jobs:
  - job: build
    displayName: Build and Test
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: DotNetCoreCLI@2
        displayName: Build solution
        inputs:
          command: "build"
          projects: "NHSD.GPIT.OrganisationImport.sln"
          arguments: "--configuration $(buildConfiguration)"

      - task: DotNetCoreCLI@2
        displayName: Run tests
        inputs:
          command: "test"
          projects: "NHSD.GPIT.OrganisationImport.sln"
          arguments: "--no-build --configuration $(buildConfiguration) -- xunit.parallelizeTestCollections=true"

      - task: DotNetCoreCLI@2
        displayName: Publish OrganisationImporter
        inputs:
          command: "publish"
          projects: "src/OrganisationImporter"
          arguments: "--configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/OrganisationImporter/App_Data/jobs/triggered/OrganisationImportWebJob -r win-x64 --no-self-contained"
          publishWebProjects: false
          modifyOutputPath: false
          zipAfterPublish: false

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: "$(Build.ArtifactStagingDirectory)/OrganisationImporter"
          includeRootFolder: false
          archiveType: "zip"
          archiveFile: "$(Build.ArtifactStagingDirectory)/OrganisationImporter/OrganisationImporter.zip"

      - task: DeleteFiles@1
        inputs:
          SourceFolder: "$(Build.ArtifactStagingDirectory)/OrganisationImporter/App_Data"
          Contents: "**"
          RemoveSourceFolder: true

      - task: PublishBuildArtifacts@1
        displayName: Package OrganisationImporter
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)/OrganisationImporter"
          ArtifactName: "OrganisationImporter"
          publishLocation: "Container"

  - job: Terraform
    displayName: Package Terraform
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: CopyFiles@2
        displayName: Copy OrgImport TF Files
        inputs:
          SourceFolder: "terraform/orgimport"
          Contents: "**"
          TargetFolder: "$(build.artifactStagingDirectory)/terraform/orgimport"
          CleanTargetFolder: false
          OverWrite: true

      - publish: $(build.artifactStagingDirectory)/terraform/orgimport
        artifact: terraform-orgimport
