variables:
  - name: dockerVersion
    value: '19.03.5'
  - name: dotnetVersion
    value: '8.0.100'
  - name: MSBUILDSINGLELOADCONTEXT
    value: '1'
  - name: buildConfiguration
    value: Release
  - group: dev-acr-secrets

trigger:
  branches:
    include:
    - develop
  paths:
    exclude:
    - "src/**"
    - "terraform/**"
    - "tests/**"
    include:
    - "src/NHSD.GPIT.BuyingCatalogue.Wagtail*"

pr:
- develop
- feature/*

jobs:
- job: version
  displayName: Work out version
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UseGitVersion@5
    displayName: gitversion
    inputs:
      versionSpec: '5.x'
  - script: echo "##vso[task.setvariable variable=semVer;isOutput=true]$(GitVersion.SemVer)"
    name: setVersionStep
  - script: echo semVer $(setVersionStep.semVer)
    name: echovar

- job: dockerBuildAndPush
  displayName: Build and Package
  variables:
    semVer: $[ dependencies.version.outputs['setVersionStep.semVer'] ]
    ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      latestTag: latest
    ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
      latestTag: latestbuild

  dependsOn: version
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: DockerInstaller@0
    inputs:
      dockerVersion: $(dockerVersion)

  - task: Docker@2
    displayName: 'Docker: Build and Push'
    condition: succeeded()
    inputs:
      containerRegistry: 'gpitfuturesdevacr'
      repository: 'nhsd/buying-catalogue/nhsdgpitbuyingcataloguewagtailapp'
      command: 'buildAndPush'
      Dockerfile: 'src/**/NHSD.GPIT.BuyingCatalogue.WagtailApp/Dockerfile'
      buildContext: './'
      tags: |
        $(semVer)
        $(latestTag)

  - task: AzureWebAppContainer@1
    displayName: 'Azure Web App on Container Deploy'
    inputs:
      appName: 'NHSD.GPIT.BuyingCatalogue.WagtailApp'
      containers: gpitfuturesdevacr/nhsd/buying-catalogue/nhsdgpitbuyingcataloguewagtailapp:$(semVer)$(latestTag)
