variables:
  - name: buildConfiguration
    value: Release

trigger:
  branches:
    include:
    - develop
  paths:
    include:
    - '**/BuyingCatalogueFunction*'
    - '**/OrganisationImporter*'

pool:
  vmImage: ubuntu-latest

jobs:
  - job: build
    displayName: Build and Test
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: DotNetCoreCLI@2
        displayName: Build solution
        inputs:
          command: "build"
          projects: 'NHSD.GPIT.OrganisationImport.sln'
          arguments: "--configuration $(buildConfiguration)"

      - task: DotNetCoreCLI@2
        displayName: Run tests
        inputs:
          command: "test"
          projects: 'NHSD.GPIT.OrganisationImport.sln'
          arguments: "--no-build --configuration $(buildConfiguration) -- xunit.parallelizeTestCollections=true"

      - task: DotNetCoreCLI@2
        displayName: Publish BuyingCatalogueFunction
        inputs:
          command: "publish"
          projects: "src/BuyingCatalogueFunction"
          arguments: "--no-build --configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/BuyingCatalogueFunction"
          publishWebProjects: false
          modifyOutputPath: false

      - task: DotNetCoreCLI@2
        displayName: Publish OrganisationImporter
        inputs:
          command: "publish"
          projects: "src/OrganisationImporter"
          arguments: "--configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/OrganisationImporter -r win-x64 --no-self-contained"
          publishWebProjects: false
          modifyOutputPath: false

      - task: PublishBuildArtifacts@1
        displayName: Package BuyingCatalogueFunction
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)/BuyingCatalogueFunction"
          ArtifactName: "BuyingCatalogueFunction"
          publishLocation: "Container"

      - task: PublishBuildArtifacts@1
        displayName: Package OrganisationImporter
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)/OrganisationImporter"
          ArtifactName: "OrganisationImporter"
          publishLocation: "Container"

  - job: Terraform
    displayName: Package Terraform
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - task: CopyFiles@2
      displayName: Copy OrgImport TF Files
      inputs:
        SourceFolder: 'terraform/orgimport'
        Contents: '**'
        TargetFolder: '$(build.artifactStagingDirectory)/terraform/orgimport'
        CleanTargetFolder: false
        OverWrite: true

    - publish: $(build.artifactStagingDirectory)/terraform/orgimport
      artifact: terraform-orgimport