version: '3.9'

services:
  nhsd.gpit.buyingcatalogue.webapp:
    image: ${DOCKER_REGISTRY}nhsdgpitbuyingcataloguewebapp
    container_name: nhsdgpitbuyingcataloguewebapp
    build:
      context: .
      dockerfile: src/NHSD.GPIT.BuyingCatalogue.WebApp/Dockerfile
