version: '3.9'

services:
    sqlserver:
        image: "mcr.microsoft.com/mssql/server"
        ports:
          - 1432:1433
        environment:
            SA_PASSWORD: "Abc123Abc123"
            ACCEPT_EULA: "Y"
                 
    nhsd_gpitbcdb_deploy:
        image: ${DOCKER_REGISTRY}gpitbuyingcataloguedatabase
        container_name: nhsd_gpitbcdb_deploy
        build:
            context: .
            dockerfile: database/NHSD.GPITBuyingCatalogue.Database.Deployment/Docker/Dockerfile
        environment:
            SA_PASSWORD: "Abc123Abc123"
            NHSD_PASSWORD: "DisruptTheMarket1!"
            HANGFIRE_PASSWORD: "Abc123Abc123"
            DB_NAME: "GPITBuyingCatalogue"
            DB_SERVER: sqlserver            
            INCLUDE_IMPORT: "TRUE"
            INCLUDE_PUBLISH: "TRUE"
            INSERT_TEST_DATA: "TRUE"
            SEED_ORGANISATIONS: "TRUE"
            CREATE_EA_USER: "True"
            EA_USER_FIRST_NAME: "Agency"
            EA_USER_LAST_NAME: "User"
            EA_USER_EMAIL: "user@agency.com"
            EA_USER_PASSWORD_HASH: "AQAAAAEAACcQAAAAEEOFkNNrFpKmDC2TBv2CP/dzxfnjdXk97RoqRlunE/CGs2tmFcewKZj4M/fITiP2tg=="
            EA_USER_PHONE: "01234567890"
        depends_on:
            - "sqlserver"    
