version: '3.9'

services:
    nhsd.gpit.buyingcatalogue.webapp:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
            - OPERATING_MODE=Private
            - BC_DB_CONNECTION=Server=sqlserver,1433;Database=buyingcatalogue;User=SA;password=Abc123Abc123;Integrated Security=false
            - ID_DB_CONNECTION=Server=sqlserver,1433;Database=CatalogueUsers;User=SA;password=8VSKwQ8xgk35qWFm8VSKwQ8xgk35qWFm!;Integrated Security=false
        ports:
            - "8000:80"      
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
        depends_on:           
            - "nhsd_bcdb_deploy"
            - "nhsd_codb_deploy"
            - "nhsd_cudb_deploy"
            - "nhsd_gpitbcdb_deploy"
            - "maildev"
            - "file.upload"

    sqlserver:
        image: "mcr.microsoft.com/mssql/server"
        ports:
          - 1432:1433
        environment:
            SA_PASSWORD: "Abc123Abc123"
            ACCEPT_EULA: "Y"

    maildev:
        image: maildev/maildev
        ports:
        - "1080:80"
        - "1081:25"

    blob.store:
        image: mcr.microsoft.com/azure-storage/azurite:3.10.0
        container_name: nhsd_bc_integration_blob_store
        ports:
        - "10100:10000"
        - "10101:10001"

    nhsd_bcdb_deploy:
        image: ${DOCKER_REGISTRY}buyingcataloguedatabase
        container_name: nhsd_bcdb_deploy
        build:
            context: .
            dockerfile: database/NHSD.BuyingCatalogue.Database.Deployment/Docker/Dockerfile
        environment:
            SA_PASSWORD: "Abc123Abc123"
            NHSD_PASSWORD: "DisruptTheMarket1!"
            DB_NAME: "BuyingCatalogue"
            DB_SERVER: sqlserver            
            INCLUDE_IMPORT: "TRUE"
            INCLUDE_PUBLISH: "TRUE"
            INSERT_TEST_DATA: "TRUE"
        depends_on:
            - "sqlserver"   

    nhsd_codb_deploy:
        image: ${DOCKER_REGISTRY}catalogueorderingdatabase
        container_name: nhsd_codb_deploy
        build:
            context: .
            dockerfile: database/NHSD.BuyingCatalogue.Ordering.OrderingDatabase.Deployment/Docker/Dockerfile
        environment:
            SA_PASSWORD: "Abc123Abc123"
            NHSD_PASSWORD: "DisruptTheMarket1!"
            DB_NAME: "CatalogueOrdering"
            DB_SERVER: sqlserver            
            INCLUDE_IMPORT: "TRUE"
            INCLUDE_PUBLISH: "TRUE"
            INSERT_TEST_DATA: "TRUE"
        depends_on:
            - "sqlserver"  
            
    nhsd_cudb_deploy:
        image: ${DOCKER_REGISTRY}catalogueusersdatabase
        container_name: nhsd_cudb_deploy
        build:
            context: .
            dockerfile: database/NHSD.BuyingCatalogue.Identity.UserDatabase.Deployment/Docker/Dockerfile
        environment:
            SA_PASSWORD: "Abc123Abc123"
            NHSD_PASSWORD: "DisruptTheMarket1!"
            DB_NAME: "CatalogueUsers"
            DB_SERVER: sqlserver            
            INCLUDE_IMPORT: "TRUE"
            INCLUDE_PUBLISH: "TRUE"
            INSERT_TEST_DATA: "TRUE"                                    
            CREATE_EA_USER: "True"
            EA_USER_FIRST_NAME: "Agency"
            EA_USER_LAST_NAME: "User"
            EA_USER_EMAIL: "user@agency.com"
            EA_USER_PASSWORD_HASH: "AQAAAAEAACcQAAAAEEOFkNNrFpKmDC2TBv2CP/dzxfnjdXk97RoqRlunE/CGs2tmFcewKZj4M/fITiP2tg=="
            EA_USER_PHONE: "01234567890"

        depends_on:
            - "sqlserver"   

    nhsd_gpitbcdb_deploy:
        image: ${DOCKER_REGISTRY}gpitbuyingcataloguedatabase
        container_name: nhsd_gpitbcdb_deploy
        build:
            context: .
            dockerfile: database/NHSD.GPITBuyingCatalogue.Database.Deployment/Docker/Dockerfile
        environment:
            SA_PASSWORD: "Abc123Abc123"
            NHSD_PASSWORD: "DisruptTheMarket1!"
            DB_NAME: "GPITBuyingCatalogue"
            DB_SERVER: sqlserver            
            INCLUDE_IMPORT: "TRUE"
            INCLUDE_PUBLISH: "TRUE"
            INSERT_TEST_DATA: "TRUE"
            CREATE_EA_USER: "True"
            EA_USER_FIRST_NAME: "Agency"
            EA_USER_LAST_NAME: "User"
            EA_USER_EMAIL: "user@agency.com"
            EA_USER_PASSWORD_HASH: "AQAAAAEAACcQAAAAEEOFkNNrFpKmDC2TBv2CP/dzxfnjdXk97RoqRlunE/CGs2tmFcewKZj4M/fITiP2tg=="
            EA_USER_PHONE: "01234567890"

        depends_on:
            - "sqlserver"  

    file.upload:
        image: ${DOCKER_REGISTRY}file-uploader
        container_name: file_uploader
        build:
            context: .
            dockerfile: azurite/Dockerfile
        depends_on:
            - "blob.store"       
