version: '3.9'

services:
    nhsd.gpit.buyingcatalogue.webapp:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
            - OPERATING_MODE=Private
            - BC_DB_CONNECTION=Server=sqlserver,1433;Database=buyingcatalogue;User=SA;password=Abc123Abc123;Integrated Security=false
            - ID_DB_CONNECTION=Server=sqlserver,1433;Database=CatalogueUsers;User=SA;password=8VSKwQ8xgk35qWFm8VSKwQ8xgk35qWFm!;Integrated Security=false
        ports:
            - "8000:80"      
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
        depends_on:
            - "sqlserver"
            - "maildev"

    sqlserver:
        image: "mcr.microsoft.com/mssql/server"
        ports:
          - 1432:1433
        environment:
            SA_PASSWORD: "Abc123Abc123"
            ACCEPT_EULA: "Y"

    maildev:
        image: maildev/maildev
        ports:
        - "1080:80"

    dacpac:
        image: ${DOCKER_REGISTRY}buyingcataloguedatabase
        container_name: mydacpac
        build:
            context: .
            dockerfile: database/NHSD.BuyingCatalogue.Database.Deployment/Docker/Dockerfile
        environment:
            SA_PASSWORD: "Abc123Abc123"
            DB_NAME: "buyingcatalogue"
            DB_SERVER: sqlserver
            NHSD_PASSWORD: "DisruptTheMarket1!"
            INCLUDE_IMPORT: "TRUE"
            INCLUDE_PUBLISH: "TRUE"
            INSERT_TEST_DATA: "TRUE"
        depends_on:
            - "sqlserver"            