CREATE TABLE catalogue.CataloguePrices
(
    CataloguePriceId INT IDENTITY(1, 1) NOT NULL,
    CatalogueItemId NVARCHAR(14) NOT NULL,
    ProvisioningTypeId INT NOT NULL,
    CataloguePriceTypeId INT NOT NULL,
    PricingUnitId SMALLINT NOT NULL,
    TimeUnitId INT NULL,
    CurrencyCode NVARCHAR(3) NOT NULL,
    PublishedStatusId INT CONSTRAINT DF_CataloguePrice_PublishedStatus DEFAULT 1 NOT NULL,
    IsLocked BIT CONSTRAINT DF_CataloguePrices_IsLocked DEFAULT 0 NOT NULL,
    LastUpdated datetime2(7) DEFAULT GETUTCDATE() NOT NULL,
    LastUpdatedBy INT NULL,
    Price DECIMAL(18, 4) NULL,
    SysStartTime DATETIME2(0) GENERATED ALWAYS AS ROW START NOT NULL,
    SysEndTime DATETIME2(0) GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME (SysStartTime, SysEndTime),
    CataloguePriceCalculationTypeId INT NULL,
    CataloguePriceQuantityCalculationTypeId INT NULL,
    CONSTRAINT PK_CataloguePrices PRIMARY KEY (CataloguePriceId),
    CONSTRAINT FK_CataloguePrices_CatalogueItem_CatalogueItemId FOREIGN KEY (CatalogueItemId) REFERENCES catalogue.CatalogueItems(Id) ON DELETE CASCADE,
    CONSTRAINT FK_CataloguePrices_ProvisioningType_ProvisioningTypeId FOREIGN KEY (ProvisioningTypeId) REFERENCES catalogue.ProvisioningTypes(Id),
    CONSTRAINT FK_CataloguePrices_CataloguePriceType_CataloguePriceTypeId FOREIGN KEY (CataloguePriceTypeId) REFERENCES catalogue.CataloguePriceTypes(Id),
    CONSTRAINT FK_CataloguePrices_CataloguePriceCalculationType FOREIGN KEY (CataloguePriceCalculationTypeId) REFERENCES catalogue.CataloguePriceCalculationTypes(Id),
    CONSTRAINT FK_CataloguePrices_CataloguePriceQuantityCalculationType FOREIGN KEY (CataloguePriceQuantityCalculationTypeId) REFERENCES catalogue.CataloguePriceQuantityCalculationTypes(Id),
    CONSTRAINT FK_CataloguePrices_PricingUnit_PricingUnitId FOREIGN KEY (PricingUnitId) REFERENCES catalogue.PricingUnits(Id),
    CONSTRAINT FK_CataloguePrices_TimeUnit_TimeUnitId FOREIGN KEY (TimeUnitId) REFERENCES catalogue.TimeUnits(Id),
    CONSTRAINT FK_CataloguePrices_LastUpdatedBy FOREIGN KEY (LastUpdatedBy) REFERENCES users.AspNetUsers(Id),
    CONSTRAINT FK_CataloguePrices_PublicationStatus FOREIGN KEY (PublishedStatusId) REFERENCES catalogue.PublicationStatus(Id),
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = catalogue.CataloguePrices_History));
