:r ./InsertCapabilityStatuses.sql
:r ./InsertCapabilityCategories.sql
:r ./InsertCompliancyLevels.sql
:r ./InsertPublicationStatuses.sql
:r ./InsertSolutionCapabilityStatuses.sql
:r ./InsertSolutionEpicStatuses.sql
:r ./InsertCatalogueItemTypes.sql
:r ./InsertFrameworks.sql
:r ./InsertCapabilities.sql
:r ./InsertCataloguePriceTypes.sql
:r ./InsertEpics.sql
:r ./InsertPricingUnits.sql
:r ./InsertProvisioningTypes.sql
:r ./InsertSuppliers.sql

:r ./InsertTimeUnits.sql
:r ./InsertSolutions.sql
:r ./InsertAdditionalServices.sql
:r ./InsertAssociatedServices.sql
:r ./DropImport.sql
:r ./DropPublish.sql

:r ./ProdLikeData/MergeSuppliers.sql
:r ./ProdLikeData/MergeCatalogueItems.sql
:r ./ProdLikeData/MergeSolutions.sql
:r ./ProdLikeData/MergeAdditionalServices.sql
:r ./ProdLikeData/MergeAssociatedServices.sql
:r ./ProdLikeData/MergeMarketingContacts.sql
:r ./ProdLikeData/MergeSolutionEpics.sql
:r ./ProdLikeData/MergeSolutionCapabilities.sql
:r ./ProdLikeData/MergeFrameworkSolutions.sql
:r ./ProdLikeData/MergeCataloguePrices.sql
