exec auditing.EnableTemporalTable 'catalogue', 'AdditionalServices'
exec auditing.EnableTemporalTable 'catalogue', 'AssociatedServices'
exec auditing.EnableTemporalTable 'catalogue', 'CatalogueItemCapabilities'
exec auditing.EnableTemporalTable 'catalogue', 'CatalogueItemEpics'
exec auditing.EnableTemporalTable 'catalogue', 'FrameworkSolutions'
exec auditing.EnableTemporalTable 'catalogue', 'MarketingContacts'
exec auditing.EnableTemporalTable 'catalogue', 'ServiceAvailabilityTimes'
exec auditing.EnableTemporalTable 'catalogue', 'ServiceLevelAgreements'
exec auditing.EnableTemporalTable 'catalogue', 'SlaContacts'
exec auditing.EnableTemporalTable 'catalogue', 'SlaServiceLevels'
exec auditing.EnableTemporalTable 'catalogue', 'Solutions'
exec auditing.EnableTemporalTable 'catalogue', 'SupplierContacts'
exec auditing.EnableTemporalTable 'catalogue', 'Suppliers'
exec auditing.EnableTemporalTable 'ordering', 'Orders'
exec auditing.EnableTemporalTable 'ordering', 'OrderItems'
GO
