CREATE TABLE ordering.Orders
(
    Id INT IDENTITY(10001, 1) NOT NULL,
    OrderNumber INT /* NOT */ NULL,
    Revision INT DEFAULT(1) /* NOT */ NULL,
    CallOffId AS CONCAT('C', FORMAT(OrderNumber, '000000'), '-', FORMAT(Revision, '00')),
    [Description] NVARCHAR(100) NOT NULL,
    OrderingPartyId INT NOT NULL,
    OrderingPartyContactId INT NULL,
    SupplierId INT NULL,
    SupplierContactId INT NULL,
    CommencementDate DATE NULL,
    FundingSourceOnlyGMS BIT NULL,
    ConfirmedFundingSource BIT NULL,
    OrderTriageValueId INT NULL,
    Created DATETIME2 CONSTRAINT DF_Order_Created DEFAULT GETUTCDATE() NOT NULL,
    LastUpdated DATETIME2 CONSTRAINT DF_Order_LastUpdated DEFAULT GETUTCDATE() NOT NULL CONSTRAINT Order_LastUpdatedNotBeforeCreated CHECK (LastUpdated >= Created),
    LastUpdatedBy INT NULL,
    Completed DATETIME2 NULL CONSTRAINT Order_CompletedNotBeforeCreated CHECK (Completed >= Created),
    OrderStatusId INT NULL,
    IsDeleted BIT CONSTRAINT DF_Order_IsDeleted DEFAULT 0 NOT NULL,
    IsTerminated BIT CONSTRAINT DF_Order_IsTerminated DEFAULT 0 NOT NULL,
    SysStartTime DATETIME2(0) GENERATED ALWAYS AS ROW START NOT NULL,
    SysEndTime DATETIME2(0) GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME (SysStartTime, SysEndTime),
    InitialPeriod INT NULL CONSTRAINT Order_PositiveInitialPeriod CHECK (InitialPeriod >= 0),
    MaximumTerm INT NULL CONSTRAINT Order_PositiveMaximumTerm CHECK (MaximumTerm >= 0),
    AssociatedServicesOnly BIT NULL,
    OrderTypeId INT NULL,
    [SolutionId] NVARCHAR(14) NULL,
    SelectedFrameworkId NVARCHAR(36) NULL,
    [DeliveryDate] DATE NULL,
    CONSTRAINT PK_Orders PRIMARY KEY (Id),
    CONSTRAINT FK_Orders_OrderingParty FOREIGN KEY (OrderingPartyId) REFERENCES organisations.Organisations (Id),
    CONSTRAINT FK_Orders_OrderingPartyContact FOREIGN KEY (OrderingPartyContactId) REFERENCES ordering.Contacts (Id),
    CONSTRAINT FK_Orders_Supplier FOREIGN KEY (SupplierId) REFERENCES catalogue.Suppliers (Id),
    CONSTRAINT FK_Orders_SupplierContact FOREIGN KEY (SupplierContactId) REFERENCES ordering.Contacts (Id),
    CONSTRAINT FK_Orders_OrderTriageValue FOREIGN KEY (OrderTriageValueId) REFERENCES ordering.OrderTriageValues(Id),
    CONSTRAINT FK_Orders_OrderStatus FOREIGN KEY (OrderStatusId) REFERENCES ordering.OrderStatus (Id),
    CONSTRAINT FK_Orders_LastUpdatedBy FOREIGN KEY (LastUpdatedBy) REFERENCES users.AspNetUsers(Id),
    CONSTRAINT FK_Orders_Solution FOREIGN KEY (SolutionId) REFERENCES catalogue.CatalogueItems(Id),
    CONSTRAINT FK_Orders_SelectedFramework FOREIGN KEY (SelectedFrameworkId) REFERENCES catalogue.Frameworks(Id),
    INDEX IX_Orders_IsDeleted (IsDeleted)
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = ordering.Orders_History));

GO
CREATE NONCLUSTERED INDEX IX_OrderNum_IsDeleted_Revision ON [ordering].[Orders] ([OrderNumber], [IsDeleted], [Revision], [OrderingPartyId], [SolutionId])
