environment                 = "$(tf_env)"
region                      = "$(tf_region)"
project                     = "$(tf_project)"
database_catalog            = "$(tf_db_catalogue)"
primary_vpn                 = "$(tf_primary_vpn)"
nhsd_network_range          = "$(tf_nhsd_network_range)"
notify_api_key              = "$(tf_notify_api_key)"
contract_expiry_template_id = "$(tf_contract_expiry_template_id)"
