environment                 = "integration"
region                      = "uksouth"
project                     = "gpitfutures"
database_catalog            = "GPITBuyingCatalogue"
primary_vpn                 = "148.253.134.213"
nhsd_network_range          = "194.101.83.0/24"
notify_api_key              = ""
contract_expiry_template_id = ""
