IF (UPPER('$(INSERT_TEST_DATA)') = 'TRUE')
BEGIN

    /*********************************************************************************************************************************************/
    /* AssociatedService */
    /*********************************************************************************************************************************************/

    CREATE TABLE #AssociatedService
    (
        CatalogueItemId nvarchar(14) NOT NULL,
        [Description] nvarchar(1000) NULL,
        OrderGuidance nvarchar(1000) NULL,
        PracticeReorganisationType int NULL,
        LastUpdated datetime2(7) NULL,
        LastUpdatedBy int NULL,
    );

    DECLARE @bobEmail AS nvarchar(50) = N'BobSmith@email.com';
    DECLARE @bobUser AS int = (SELECT Id FROM users.AspNetUsers WHERE Email = @bobEmail);

    INSERT INTO #AssociatedService (CatalogueItemId, [Description], OrderGuidance, PracticeReorganisationType, LastUpdated, LastUpdatedBy) 
         VALUES 
                (N'100000-001', 
                N'Additional minutes for video consultations.', 
                N'The typical number of units ordered is one. There is no maximum number that can be ordered.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10000-001', 
                N'Initial configuration and set up of the system. This applies to the implementation phase.', 
                N'Installations will be on an individual basis (one) to overarching organisations, such as Federations, CSGs or PCNs.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10000-002', 
                N'EMIS Health can provide training services for Enterprise Search and Reports which are flexible and can be tailored to meet local requirements. These can be for live operations or used during the implementation phase. The maximum number of attendees is six.', 
                N'A typical amount of training days for a new installation is likely to be six days. Additional training is available and would obviously be dependant on scale and user needs. Training is available on a needs basis. This could be one day or purchased in bulk.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10000-054', 
                N'Customers can optionally separately purchase a qualified Egton Engineer’s time in half day increments to assist with moving or re-positioning Automated Arrivals equipment.', 
                N'The typical number of units ordered is one. There should be no requirement to order more than one', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10000-062', 
                N'Enterprise Search and Reports is the fast and efficient way to source, search and report on GP data in real time.', 
                N'With the ability to develop custom searches, you can measure against your key objective, including QOF, LESs/DESs, referral activity and immunisations.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'100001-001', 
                N'A solution to improve practice efficiency and patient experience.', 
                N'Patients use a touchscreen to check-in and get an instruction on arrival and book available future appointments. Staff control the kiosk from a central portal for messages to patient groups and confirming personal data.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'100002-001', 
                N'The integrated device is pre-loaded & configured with Anywhere Consult software, and also has Windows 10 operating system and Microsoft Office Professional installed.',  
                N'The typical number of units ordered is one. There is no maximum number of units that can be ordered.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'100003-001', 
                N'Five day course delivered onsite, providing in-depth training, allowing attendees to specialise in a wide range of SystmOne functionality. This service should be purchased by organisations wanting to enhance the training provided with the deployment of the Solution or Service. Super User Training ensures that users have the expertise to optimise the use of the Solution or Service across their organisation. Training can be tailored to suit a wide range of needs. Suitable for up to 8 attendees. A full day is 10am-4pm on site.', 
                N'Dependent on business need. Purchase of training course is at the organisations discretion, it is not mandatory. There is no maximum number of courses purchased. Each course can accommodate up to 8 attendees; additional course(s) would need to be purchased if the number of attendees exceeds this.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'100004-001', 
                N'The SystmOne GP Deployment - Full Training needs to be purchased for any practice migrating onto SystmOne without any training support from another organisation (e.g. their CCG).\r\n\r\nThis service includes:\r\n - Dedicated migration services to enable the secure transfer of data from a single Source Solution to SystmOne GP.\r\n- A comprehensive SystmOne GP End User Training course led by TPP Product Specialists, including pre and post GoLive support.\r\n- Training schedule: 5 Full Training Days to prepare for the deployment, 2 Full Training Days for technical and business Go-Live and 3 Full Training Days for post Go-Live support. This totals 10 Full Training Days.\r\nBy purchasing this service, a practice will ensure their data is successfully migrated from the incumbent system and all practice staff are fully trained on SystmOne.',
                N'Every practice migrating onto SystmOne will need to purchase either the SystmOne GP Deployment with Full Training or the SystmOne GP Deployment with Go Live Support. Maximum number required regardless of practice size is one.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'100005-001', 
                N'The SystmOne GP Deployment - Go-Live Support will be purchased by any practice migrating onto SystmOne where they have training support from another organisation (e.g. from their CCG).\r\n\r\nThis includes:\r\n\- Dedicated migration services to enable the secure transfer of data from a single Source Solution to SystmOne GP.\r\n- Go-Live Support: 2 Full Training Days to cover Technical and Business Go-Live. Data migration with Go-Live support only is appropriate where CCGs have their own SystmOne-accredited training team to provide training to end users\r\nBy purchasing this service, a practice will ensure their data is migrated from the incumbent system with support from TPP during the Go Live.', 
                N'Every practice migrating onto SystmOne will need to purchase either the SystmOne GP Deployment with Full Training or the SystmOne GP Deployment with Go Live Support. Maximum number required regardless of practice size is one', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10000-S-001', 
                N'Additional minutes for video consultations.', 
                N'The typical number of units ordered is one. There is no maximum number that can be ordered.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10000-S-002', 
                N'Initial configuration and set up of the system. This applies to the implementation phase.', 
                N'Installations will be on an individual basis (one) to overarching organisations, such as Federations, CSGs or PCNs.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10000-S-003', 
                N'EMIS Health can provide training services for Enterprise Search and Reports which are flexible and can be tailored to meet local requirements. These can be for live operations or used during the implementation phase. The maximum number of attendees is six.', 
                N'A typical amount of training days for a new installation is likely to be six days. Additional training is available and would obviously be dependant on scale and user needs. Training is available on a needs basis. This could be one day or purchased in bulk.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10000-S-004', 
                N'Customers can optionally separately purchase a qualified Egton Engineer’s time in half day increments to assist with moving or re-positioning Automated Arrivals equipment.', 
                N'The typical number of units ordered is one. There should be no requirement to order more than one', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10000-S-005', 
                N'Enterprise Search and Reports is the fast and efficient way to source, search and report on GP data in real time.', 
                N'With the ability to develop custom searches, you can measure against your key objective, including QOF, LESs/DESs, referral activity and immunisations.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10000-S-006', 
                N'A solution to improve practice efficiency and patient experience.', 
                N'Patients use a touchscreen to check-in and get an instruction on arrival and book available future appointments. Staff control the kiosk from a central portal for messages to patient groups and confirming personal data.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10000-S-009', 
                N'The integrated device is pre-loaded & configured with Anywhere Consult software, and also has Windows 10 operating system and Microsoft Office Professional installed.',  
                N'The typical number of units ordered is one. There is no maximum number of units that can be ordered.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10000-S-036', 
                N'This service ensure practice infrastructure is in place and has optimum configuration. This service is applicable to the implementation phase and live operations.', 
                N'Dependent on the issue, a typical range is 1-7 days. Additional Engineering is available and would be dependant on scale and user needs. This could be one day or purchased in bulk.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10000-S-037', 
                N'A fully managed, ISO compliant, service for the digitisation of Lloyd George records. We’ll collect your paper records, scan them and upload them into EMIS Web as digital files. Following sign-off paper records are securely destroyed by shredding them and then recycling them in an eco-friendly way.', 
                N'The typical volume would be an average of eight thousand which is the typical practice capitation. The largest practice size is the maximum.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10000-S-038', 
                N'We will take digitised Lloyd George files and upload them into EMIS Web. This allows for full visibility of a patients medical records from within the clinical system for more informed decisions at the point of care.', 
                N'The typical volume would be an average of eight thousand which is the typical practice capitation. The largest practice size is the maximum.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10000-S-039', 
                N'This service ensures that data is transferred as comprehensively, accurately and as quickly as possible, preserving its context and meaning. EMIS Health understands the importance of minimising the disruption during the data migration. This service applies to the implementation phase.', 
                N'The typical unit of order is expected to be on an individual practice migration basis (one). Migrations could potentially be ordered for a whole CCG if there was a bulk request (up to one hundred).', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10000-S-069', N'Doc Management – Migration is expected to be on an individual practice migration basis (one).', 
                N'The typical unit of order is expected to be on an individual practice migration basis (one). Migrations could potentially be ordered for a whole CCG if there was a bulk request (up to one hundred).', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10000-S-040', 
                N'Our practice reorganisation service provides support during practice splits and mergers. When two or more practices decide to split or merge clinical information, our service can target either select patients or the full patient list. It makes organising a change in practice simple. This service is applicable to both implementation and live operations.', 
                N'The typical unit of order for practice mergers and splits is likely to be on an individual basis (one). This is a fixed fee per practice regardless of size.', 
                3, -- merger and split
                GETUTCDATE(), 
                @bobUser),
                (N'10000-S-041', 
                N'Our project management service can help organisations to seamlessly manage end-to-end projects based on their requirements. From initial planning to roll-out and ongoing project management, our team provides tailored support to customers.', 
                N'Project Management resource is anticipated to be low for standard installations. For more complex deployments it is anticipated to be higher. The minimum is 1 day, maximum is 10 days per practice.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10000-S-042', 
                N'Our service provides support during practice mergers. When two or more practices decide to split or merge clinical information, our service can target either select patients or the full patient list. It makes organising a change in practice simple. This service is applicable to both implementation and live operations.', 
                N'The typical unit of order for practice mergers and splits is likely to be on an individual basis (one). This is a fixed fee per practice regardless of size.', 
                1, -- merger
                GETUTCDATE(), 
                @bobUser),
                (N'10000-S-043', 
                N'Our service provides support during practice splits . When two or more practices decide to split or merge clinical information, our service can target either select patients or the full patient list. It makes organising a change in practice simple. This service is applicable to both implementation and live operations.', 
                N'The typical unit of order for practice mergers and splits is likely to be on an individual basis (one). This is a fixed fee per practice regardless of size.', 
                2, -- split
                GETUTCDATE(), 
                @bobUser),
                (N'10000-S-007', 
                N'Customers can optionally separately purchase a qualified Egton Engineer’s time in half day increments to assist with moving or re-positioning Automated Arrivals equipment.', 
                N'The typical number of units ordered is one. There should be no requirement to order more than one', 
                0,
                GETUTCDATE(), 
                @bobUser),                
                (N'10000-S-008', 
                N'Egton can provide additional specialist services for network cabling from the Automated Arrivals endpoint up to the patch panel outside the server equipment room.', 
                N'The typical number of units ordered is one. There should be no requirement to order more than one', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10047-S-001', 
                N'Pathfinder can provide additional specialist services for network cabling.', 
                N'The typical number of units ordered is one. There should be no requirement to order more than one.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10047-S-002', 
                N'Transform service can target either select patients or the full patient list.', 
                N'The typical unit of order for practice mergers and splits is likely to be on an individual basis (one).', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10004-S-002', 
                N'Customisation importance of minimising the disruption during the data migration. This service applies to the implementation phase.', 
                N'The typical unit of order is expected to be on an individual practice migration basis (one). Migrations could potentially be ordered for a whole CCG if there was a bulk request (up to one hundred).', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10004-S-004', 
                N'Supports the secure migration of Practice data between Solutions.', 
                N'Migrations could potentially be ordered for a whole CCG if there was a bulk request (up to one hundred).', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10004-S-003', 
                N'A group training session for CCG & practice staff on the use of the solution. There is no specific limit on how many staff or practices can attend the training, but 20-30 is a typical number. The commissioning organisation usually makes the venue available at their own cost.', 
                N'A commissioning organisation will usually require a single training seminar to cover all participating practices. Multiple seminar days can be booked to work with fewer numbers of participants, or to assist with geographical outreach.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10004-S-001', 
                N'EMIS Health can provide a wide range of training services which are flexible and can be tailored to meet local requirements or goals. Our experienced training team will support you in using your clinical system to its full potential and ensure patient data is captured correctly and effectively. This service is applicable to both the implementation phase and live operations', 
                N'A typical amount of training days for a new installation is likely to be six days. Additional training is available and would obviously be dependant on scale and user needs. Training is available on a needs basis. This could be one day or purchased in bulk.', 
                0,
                GETUTCDATE(), 
                @bobUser),                
                (N'10073-S-021', 
                N'Setup/Provisioning/Launch seamlessly manage end-to-end projects based on their requirements.', 
                N'Project Management resource is anticipated to be low for standard installations. For more complex deployments it is anticipated to be higher.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10073-S-023', 
                N'My GP Integration is anticipated to be low for standard installations. For more complex deployments', 
                N'resource is anticipated to be low for standard installations. For more complex deployments it is anticipated to be higher.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10029-S-007', 
                N'Business Analysis is a research discipline of identifying business needs and determining solutions to business problems.', 
                N'Solutions often include a software-systems development component, but may also consist of process improvements, organizational change or strategic planning and policy development.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10029-S-009', 
                N'Information Architecture is the structural design of shared information environments', 
                N'Typically, it involves a model or concept of information that is used and applied to activities which require explicit details of complex information systems.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10007-S-001', 
                N'Provides for adding and customising of any local content (e.g. ref forms & pathways) that exceed the 100 free document included in annual license fee. Ensures currency of local content & consistency of treatment guidelines.', 
                N'The typical unit of order ranges from 50 to 100 document. There is no minimum and maximum unit of order.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10007-S-002', 
                N'For practices that currently have the solution database installed locally at their practice, enables these databases to be moved to a centrally hosted server on the NHS secure network or; Provides for the migration of the solution from the existing clinical system to a new one.', 
                N'To migrate the system from a practice hosted database to a centrally hosted database or migrate from the existing clinical system to a new system will typically require one day per practice. There is no maximum number.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10007-S-003', 
                N'Provides for the remote installation of the solution at each of the required practices and workstations plus registering of users enabling role based access and user preferences. Following this the system is live for on-site training and operational use.', 
                N'The typical number of units ordered equals the number of practices to which the solution needs to be deployed. As an example, an order for 40 practices will equal 40 units. There are no maximum units of order.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10007-S-004', 
                N'Provides for the enhancement of user workflow between tools in the clinical system (e.g. templates) and content within DXS Best Pathway or any other discrete project based requirements. e.g. linking local templates to appropriate content for easy access', 
                N'There is no typical unit of order as requirements are defined by the client. There is no maximum unit of order.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10007-S-005', 
                N'To ensure max use of the solution provides for on-site training of practice staff after deployment at each practice. Supported by comprehensive printed & online training material. Additional training can be purchase under Associate Services.', 
                N'Typical unit of order equals one full days face to face training at a chosen venue for all practice staff requiring training. There are no maximum units of order.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10029-S-006', 
                N'Our project management service can help organisations to seamlessly manage end-to-end projects based on their requirements. From initial planning to roll-out and ongoing project management, our team provides tailored support to customers.', 
                N'Project Management resource is anticipated to be low for standard installations. For more complex deployments it is anticipated to be higher. The minimum is 1 day, maximum is 10 days per practice.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10029-S-008', 
                N'Solutions development determines the best way of satisfying the requirements for an output.', 
                N'select the optimum solution; create a specification for the solution.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10029-S-010', 
                N'Staff training is a programme implemented by a manager or person of authority to provide specific staff members with the necessary skills and knowledge for their current role.', 
                N'It is often compulsory for some level of training to be offered to new members of staff as you prepare them for their role.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10052-S-012', 
                N'Data extraction services help tap the vast data resources available online or within internal sources and extract the data so that it can be used to benefit the business.', 
                N'This post is a data extraction services guide to help you with your data management.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10052-S-001', 
                N'One day of training by a TPP Product Specialist. Training can be tailored to suit a wide range of needs. For example, training could be focussed on a specific area of system functionality or a particular workflow. A full day is 10am-4pm. The Product Specialist will attend on site.', 
                N'Purchase of training days is at the buyers discretion and dependent on business need. The number of days required will vary depending on what training is required.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10052-S-002', 
                N'One half-day of training by a TPP Product Specialist. Training can be tailored to suit a wide range of needs. For example, training could be focussed on a specific area of system functionality or a particular workflow. A half-day is 10am-1pm or 1pm-4pm. The Product Specialist will attend on site', 
                N'Purchase of training days is at the buyers discretion and dependent on business need. The number of days required will vary depending on what training is required - for example, whether this is to train new staff on the system or just to enhance users knowledge of functionality. There are no minimum or maximum units of order', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10052-S-009', 
                N'This service merges a single SystmOne GP unit into another. This service will be required by organisations who previously operated independently but are planning to merge their services, and so need to share a single instance of their software solution.\r\n\r\nPurchasing will allow two practices will combine the elements of both units (including patient lists, staff members, caseloads, etc.) into a single SystmOne unit.', 
                N'Dependent on business need. This Associated Service (and corresponding fee) is for two practices merging into one, regardless of practice size. If more than two practices are merging, an additional Practice Merge will need to be purchased for each additional practice.', 
                1, -- merger
                GETUTCDATE(), 
                @bobUser),
                (N'10052-S-010', 
                N'This service splits a single SystmOne GP unit into two units. This service will be required by organisations who previously operated as one practice and are splitting into separate organisations.\r\n\r\nA Practice Split will allow an organisation currently working as a single entity to separate business elements between two individual SystmOne units. Patient records will be split between the two units.', 
                N'Dependent on business need. This Associated Service (and corresponding fee) is for one GP practice splitting into two, regardless of practice size. If the practice is splitting into more than two new entities, an additional Practice Split will need to be purchased for each additional new practice.', 
                2, -- split
                GETUTCDATE(), 
                @bobUser),
                (N'10052-S-011', 
                N'This service can be purchased where an organisation wants to transfer deducted patient data and/or audit data to a secured portable USB device at the point of a migration to SystmOne GP. This service is to ensure, where necessary, the provision of deducted patient records taken from the incoming practice legacy system, which are not migrated onto SystmOne GP.\r\nThese records are not migrated as the patients are no longer receiving care at that practice. The USB can also be requested for audit purposes. Practices will be provided with a USB holding the data.', 
                N'Dependent on business need. Maximum purchase required is typically one USB per practice. The practice size does not affect the number of USBs required.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10052-S-003', 
                N'Five day course delivered onsite, providing in-depth training, allowing attendees to specialise in a wide range of SystmOne functionality. This service should be purchased by organisations wanting to enhance the training provided with the deployment of the Solution or Service. Super User Training ensures that users have the expertise to optimise the use of the Solution or Service across their organisation. Training can be tailored to suit a wide range of needs. Suitable for up to 8 attendees. A full day is 10am-4pm on site.', 
                N'Dependent on business need. Purchase of training course is at the organisations discretion, it is not mandatory. There is no maximum number of courses purchased. Each course can accommodate up to 8 attendees; additional course(s) would need to be purchased if the number of attendees exceeds this.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10052-S-013', 
                N'The SystmOne GP Deployment - Full Training needs to be purchased for any practice migrating onto SystmOne without any training support from another organisation (e.g. their CCG).\r\n\r\nThis service includes:\r\n - Dedicated migration services to enable the secure transfer of data from a single Source Solution to SystmOne GP.\r\n- A comprehensive SystmOne GP End User Training course led by TPP Product Specialists, including pre and post GoLive support.\r\n- Training schedule: 5 Full Training Days to prepare for the deployment, 2 Full Training Days for technical and business Go-Live and 3 Full Training Days for post Go-Live support. This totals 10 Full Training Days.\r\nBy purchasing this service, a practice will ensure their data is successfully migrated from the incumbent system and all practice staff are fully trained on SystmOne.',
                N'Every practice migrating onto SystmOne will need to purchase either the SystmOne GP Deployment with Full Training or the SystmOne GP Deployment with Go Live Support. Maximum number required regardless of practice size is one.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10052-S-008', 
                N'The SystmOne GP Deployment - Go-Live Support will be purchased by any practice migrating onto SystmOne where they have training support from another organisation (e.g. from their CCG).\r\n\r\nThis includes:\r\n\- Dedicated migration services to enable the secure transfer of data from a single Source Solution to SystmOne GP.\r\n- Go-Live Support: 2 Full Training Days to cover Technical and Business Go-Live. Data migration with Go-Live support only is appropriate where CCGs have their own SystmOne-accredited training team to provide training to end users\r\nBy purchasing this service, a practice will ensure their data is migrated from the incumbent system with support from TPP during the Go Live.', 
                N'Every practice migrating onto SystmOne will need to purchase either the SystmOne GP Deployment with Full Training or the SystmOne GP Deployment with Go Live Support. Maximum number required regardless of practice size is one', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10052-S-004', 
                N'Web based Train the Trainer course, associated materials, on line, content and document resources and support for Call off Ordering Party trainers, so they can implement the service as intended correctly and safely.', 
                N'Usually x1 course per call off where a call off = 1 CCG Larger scale call offs typically x1 course per 3 CCGs', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10046-S-001', 
                N'Provides consultancy and support to complete Core GP Connect onboarding and activation process with call off ordering party GP Practices.', 
                N'x1 Per Call Off', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10046-S-002', 
                N'If a practice merges with another or if the practice is splitting in to two or more, this service will deliver the required Docman technical work, working with your clinical system supplier. Only 1 day is required for a merger or practice split, each practice does not have to purchase separate days', 
                N'New Customers:\r\nTypical Quantity - 1 day\r\nExisting Customers:\r\nTypical Quantity - 1 day', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10046-S-003', 
                N'A remote training day that can be purchased and used as the customer requires for example, health checks, Q&A sessions or a day designed by the customer to meet the Practice needs. A remote day is delivered via telephone, skype or webex depending upon the requirement of the practice', 
                N'New Customers:\r\nTypical Quantity - 1 day\r\nExisting Customers:\r\nTypical Quantity - 1 day\r\n', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10046-S-004', 
                N'Two days on-site training for Docman10X for new customers.\r\nAdditional on-site training can be purchased for example,\r\ntraining new staff, health checks or a day designed by the customer to meet the Practice needs. If purchasing more than one day of training, then the days must be used consecutively', 
                N'New Customers:\r\nTypical Quantity - 1 day\r\nExisting Customers:\r\nTypical Quantity - 2 days', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10046-S-005', 
                N'Pre-deployment, deployment, sustainment, re-deployment and post-deployment.', 
                N'Each stage is characterized both by a time frame and specific emotional challenges, which must be dealt with and mastered by each of the Family members.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10046-S-006', 
                N'Post-deployment, deployment, sustainment, re-deployment and post-deployment.', 
                N'Each stage is characterized both by a time frame and specific emotional challenges, which must be dealt with and mastered by each of the Family members.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10046-S-007', 
                N'A remote day that is purchased to migrate the Docman 7 data into the new Docman10X environment', 
                N'New Customers:\r\n Typical Quantity - 1 day\r\nExisting Customers:\r\nTypical Quantity - 1 day', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10046-S-009', 
                N'Docman 10 is a scanning and document management system, which integrates with Vision to enable documents to be scanned and filed into the patient record.',
                N'Docman 10 is a scanning and document management system, which integrates with Vision to enable documents to be scanned and filed into the patient record.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10046-S-010', 
                N'A remote day for new Docman customer to enable the database creation and technical activities to generate the new Docman10X system', 
                N'New Customers:\r\nTypical Quantity - 1 day\r\nExisting Customers:\r\nTypical Quantity - 1 day', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10063-S-004', 
                N'Implementation services rely on a structured, comprehensive approach from design to testing to help you achieve optimal outcomes from your software solution quickly.', 
                N'It takes the right mix of industry and technology expertise to realize successful software deployments that help you advance your business.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10063-S-005', 
                N'Implementation service needed to enable deployment of Core software components and integration services to GP Practices by Call Off Ordering Party or their agent e.g. CSU GP IT\r\nsupport service. This provides software components to integrate with source clinical system and enable access and operation of the solution.', 
                N'Service usually purchased at CCG or STP scale which means practice numbers can be from 15 to more than 200', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10063-S-006', N'Support services provide internal support to the main business of organization.', 
                N'Activities provided to or on behalf of a person in the areas of personal care and assistance and property maintenance in order to allow a person to live in the least restrictive environment.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10063-S-007', N'Defines the training activities and collateral expected from Suppliers to support the buyers and users of their Solutions.', 
                N'A typical amount of training for a new installation is likely to be one day. Additional training is available and would obviously be dependant on scale and user needs. Training is available on a needs basis. This could be one day or purchased in bulk.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10063-S-008', 
                N'EMIS Health can provide a wide range of training services which are flexible and can be tailored to meet local requirements or goals. These can be for live operations or used during the implementation phase. The maximum number of attendees is six.', 
                N'The typical number of units ordered is one. There is no maximum number of units that can be ordered.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10063-S-009', 
                N'A group training session for CCG & practice staff on the use of the solution. There is no specific limit on how many staff or practices can attend the training, but 20-30 is a typical number. The commissioning organisation usually makes the venue available at their own cost.', 
                N'A commissioning organisation will usually require a single training seminar to cover all participating practices. Multiple seminar days can be booked to work with fewer numbers of participants, or to assist with geographical outreach.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10063-S-010', N'Form and Document Creation is one of the things that technical communicators do as part of creating deliverables for their companies or clients.', 
                N'Document design is: "the field of theory and practice aimed at creating comprehensible, persuasive and usable functional documents', 
                0,
                GETUTCDATE(), @bobUser),
                (N'10052-S-005', 
                N'This Associated Service is purchased by buyers for training and testing purposes. The training environment is a near-replica of the live SystmOne environment and is updated in line with updates to the live system. It can be accessed by multiple users simultaneously. Configuration of the environment and the creation of test data to be done by the Call Off Ordering Party. Additional Services can be enabled, on request, at the Training Environment purchased for the applicable Solution, with the exception of Mobile Working which requires a different (separate) training environment.', 
                N'Dependent on business need and contracting organisations approach to training. For example, a CCG with a central training team may purchase one training unit for demonstrating functionality to different practices, or each GP practice may wish to have their own training environment.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10072-S-005', N'Push Access - Implementation DESCRIPTION', N'',
                0,
                GETUTCDATE(), @bobUser),
                (N'10072-S-010', 
                N'Initial configuration and set up of the system. This service is applicable to the Implementation phase.', 
                N'Installations will be on an individual basis (one) to practices although CCGs might purchase this in bulk for multiple practices.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10072-S-011', 
                N'Initial configuration and set up of the system. This service is applicable to the Implementation phase.', 
                N'Installations will be on an individual basis (one) to practices although CCGs might purchase this in bulk for multiple practices.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10072-S-012', 
                N'This can be used at any time to provide refresher training for new teams ', 
                N'You can order this at any time during the life of the service. This can be split across multiple practices within a PCN, Federation or ICS up to 12 attendees ', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10072-S-013', 
                N'We will provide a banner for your surgery, leaflets for patient information and can provide digital assets for your website to enable you to advertise your new digital service to your patients', 
                N'Surgeries can order at multiple times during the life of the service, although we generally recommend that this is used when the service is first activated', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10046-S-008', 
                N'End to end accredited training courses with conceptual information, interactions, simulations, video demonstrations and quizzes. Course progress is trackable by practice and/or IT managers if required.', 
                N'', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10030-S-001', 
                N'One SMS message credits consists of 160 characters. Messages longer than this will use an additional credit, with each subsequent credit consisting of up to 150 characters.', 
                N'Typical Units and minimum order size 10,000 fragment bundle. No Maximum order size', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10073-S-022', 
                N'If required group or individual User Training programmes can be undertaken and will be charged based on standard session rates.', 
                N'Typical units of order 1 (existing customer). Typical units of order 2 (new customer). No maximum order size.', 
                0,
                GETUTCDATE(), 
                @bobUser),
                (N'10000-S-141', N'Online and Video Consult – Implementation DESCRIPTION', N'',
                0,
                GETUTCDATE(), @bobUser);

    MERGE INTO catalogue.AssociatedServices AS TARGET
    USING #AssociatedService AS SOURCE
    ON TARGET.CatalogueItemId = SOURCE.CatalogueItemId 
    WHEN MATCHED THEN
           UPDATE SET TARGET.[Description] = SOURCE.[Description],
                      TARGET.OrderGuidance = SOURCE.OrderGuidance,
                      TARGET.PracticeReorganisationType = SOURCE.PracticeReorganisationType,
                      TARGET.LastUpdated = SOURCE.LastUpdated,
                      TARGET.LastUpdatedBy = SOURCE.LastUpdatedBy
    WHEN NOT MATCHED BY TARGET THEN
    INSERT (CatalogueItemId, [Description], OrderGuidance, PracticeReorganisationType, LastUpdated, LastUpdatedBy)
    VALUES (SOURCE.CatalogueItemId, SOURCE.[Description], SOURCE.OrderGuidance, SOURCE.PracticeReorganisationType, SOURCE.LastUpdated, SOURCE.LastUpdatedBy);
END;
GO
