using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Identity;
using NHSD.GPIT.BuyingCatalogue.E2ETests.Database;
using NHSD.GPIT.BuyingCatalogue.EntityFramework;
using NHSD.GPIT.BuyingCatalogue.EntityFramework.Addresses.Models;
using NHSD.GPIT.BuyingCatalogue.EntityFramework.Organisations.Models;
using NHSD.GPIT.BuyingCatalogue.EntityFramework.Users.Models;
using NHSD.GPIT.BuyingCatalogue.ServiceContracts.Identity;

namespace NHSD.GPIT.BuyingCatalogue.E2ETests.Utils.SeedData
{
    internal static class UserSeedData
    {
        internal const string AliceEmail = "AliceSmith@email.com";
        internal const string DaveEmail = "DaveSmith@email.com";
        internal const int BobId = 2;
        internal const int SueId = 3;
        internal const int AliceId = 4;
        internal const int DaveId = 5;
        private const string TestPassword = "Th1sIsP4ssword!";

        internal static void Initialize(BuyingCatalogueDbContext context)
        {
            AddDefaultData(context);
        }

        private static void AddDefaultData(BuyingCatalogueDbContext context)
        {
            var buyerRole = context.Roles.First(r => r.Name == OrganisationFunction.Buyer.Name);
            var adminRole = context.Roles.First(r => r.Name == OrganisationFunction.Authority.Name);
            var accountManagerRole = context.Roles.First(r => r.Name == OrganisationFunction.AccountManager.Name);

            var bobOrganisation = new Organisation
            {
                Id = 1,
                Name = "NHS ENGLAND - X26",
                Address = new Address
                {
                    Line1 = "1 TREVELYAN SQUARE",
                    Town = "LEEDS",
                    Postcode = "LS1 6AE",
                    Country = "ENGLAND",
                },
                InternalIdentifier = "EA-X26",
                ExternalIdentifier = "X26",
                OrganisationType = OrganisationType.EA,
                PrimaryRoleId = "RO116",
                LastUpdated = DateTime.UtcNow,
            };

            var sueOrganisation = new Organisation
            {
                Id = 77,
                Name = "NHS Hull CCG",
                Address = new Address
                {
                    Line1 = "WILBERFORCE COURT",
                    Line2 = "ALFRED GELDER STREET",
                    Town = "HULL",
                    Postcode = "HU1 1UY",
                    Country = "ENGLAND",
                },
                InternalIdentifier = "CG-03F",
                ExternalIdentifier = "03F",
                OrganisationType = OrganisationType.CCG,
                PrimaryRoleId = "RO98",
                LastUpdated = DateTime.UtcNow,
            };

            var aliceOrganisation = new Organisation
            {
                Id = 83,
                Name = "NHS Leeds CCG",
                Address = new Address
                {
                    Line1 = "SUITES 2 - 4 WIRA HOUSE",
                    Line2 = "RING ROAD",
                    Line3 = "WEST PARK",
                    Town = "LEEDS",
                    County = "WEST YORKSHIRE",
                    Postcode = "LS16 6EB",
                    Country = "ENGLAND",
                },
                InternalIdentifier = "CG-15F",
                ExternalIdentifier = "15F",
                OrganisationType = OrganisationType.CCG,
                PrimaryRoleId = "RO98",
                LastUpdated = DateTime.UtcNow,
                RelatedOrganisationOrganisations = new HashSet<RelatedOrganisation>
                {
                    new RelatedOrganisation(83, 2),
                    new RelatedOrganisation(83, 3),
                },
            };

            var daveOrganisation = new Organisation
            {
                Id = 176,
                Name = "South West North Commissioning Hub",
                Address = new Address
                {
                    Line1 = "NHS ENGLAND",
                    Line2 = "QUARRY HOUSE",
                    Line3 = "QUARRY HILL",
                    Town = "LEEDS",
                    County = "WEST YORKSHIRE",
                    Postcode = "LS2 7UE",
                    Country = "ENGLAND",
                },
                InternalIdentifier = "CG-15H",
                ExternalIdentifier = "15H",
                OrganisationType = OrganisationType.CCG,
                PrimaryRoleId = "RO98",
                LastUpdated = DateTime.UtcNow,
            };

            // Organisations
            List<Organisation> organisations = new()
            {
                new Organisation { Id = 2, Name = "Cheshire and Merseyside Commissioning Hub", Address = new Address { Line1 = "C/O NHS ENGLAND, 1W09, 1ST FLOOR", Line2 = "QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", County = "WEST YORKSHIRE", Postcode = "LS2 7UE", Country = "ENGLAND" }, PrimaryRoleId = "RO98", LastUpdated = DateTime.UtcNow, ExternalIdentifier = "13Y", InternalIdentifier = "CG-13Y", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 4, Name = "Cumbria and North East – H&J Commissioning Hub", Address = new Address { Line1 = "C/O NHS ENGLAND", Line2 = "1W09, 1ST FLOOR, QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", County = "WEST YORKSHIRE", Postcode = "LS2 7UE", Country = "ENGLAND" }, PrimaryRoleId = "RO98", LastUpdated = DateTime.UtcNow, ExternalIdentifier = "14P", InternalIdentifier = "CG-14P", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 3, Name = "Cumbria and North East Commissioning Hub", Address = new Address { Line1 = "C/O NHS ENGLAND, 1W09, 1ST FLOOR", Line2 = "QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", County = "WEST YORKSHIRE", Postcode = "LS2 7UE", Country = "ENGLAND" }, PrimaryRoleId = "RO98", LastUpdated = DateTime.UtcNow, ExternalIdentifier = "13X", InternalIdentifier = "CG-13X", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 6, Name = "East – H&J Commissioning Hub", Address = new Address { Line1 = "C/O NHS ENGLAND", Line2 = "1W09, 1ST FLOOR, QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", County = "WEST YORKSHIRE", Postcode = "LS2 7UE", Country = "ENGLAND" }, PrimaryRoleId = "RO98", LastUpdated = DateTime.UtcNow, ExternalIdentifier = "14R", InternalIdentifier = "CG-14R", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 5, Name = "East Commissioning Hub", Address = new Address { Line1 = "C/O NHS ENGLAND, 1W09, 1ST FLOOR", Line2 = "QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", County = "WEST YORKSHIRE", Postcode = "LS2 7UE", Country = "ENGLAND" }, PrimaryRoleId = "RO98", LastUpdated = DateTime.UtcNow, ExternalIdentifier = "14E", InternalIdentifier = "CG-14E", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 7, Name = "Greater Manchester Commissioning Hub", Address = new Address { Line1 = "4TH FLOOR", Line2 = "PICCADILLY PLACE", Line3 = "LONDON ROAD", Town = "MANCHESTER", Postcode = "M1 3BN", Country = "ENGLAND" }, PrimaryRoleId = "RO98", LastUpdated = DateTime.UtcNow, ExternalIdentifier = "14J", InternalIdentifier = "CG-14J", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 9, Name = "Hampshire, Isle of Wight and Thames Valley – H&J Commissioning Hub", Address = new Address { Line1 = "C/O NHS ENGLAND", Line2 = "1W09, 1ST FLOOR, QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", County = "WEST YORKSHIRE", Postcode = "LS2 7UE", Country = "ENGLAND" }, PrimaryRoleId = "RO98", LastUpdated = DateTime.UtcNow, ExternalIdentifier = "14W", InternalIdentifier = "CG-14W", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 8, Name = "Hampshire, Isle of Wight and Thames Valley Commissioning Hub", Address = new Address { Line1 = "NHS ENGLAND", Line2 = "QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", County = "WEST YORKSHIRE", Postcode = "LS2 7UE", Country = "ENGLAND" }, PrimaryRoleId = "RO98", LastUpdated = DateTime.UtcNow, ExternalIdentifier = "15J", InternalIdentifier = "CG-15J", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 11, Name = "Kent, Surrey and Sussex – H&J Commissioning Hub", Address = new Address { Line1 = "C/O NHS ENGLAND", Line2 = "1W09, 1ST FLOOR, QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", County = "WEST YORKSHIRE", Postcode = "LS2 7UE", Country = "ENGLAND" }, PrimaryRoleId = "RO98", LastUpdated = DateTime.UtcNow, ExternalIdentifier = "14V", InternalIdentifier = "CG-14V", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 10, Name = "Kent, Surrey and Sussex Commissioning Hub", Address = new Address { Line1 = "NHS ENGLAND", Line2 = "QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", County = "WEST YORKSHIRE", Postcode = "LS2 7UE", Country = "ENGLAND" }, PrimaryRoleId = "RO98", LastUpdated = DateTime.UtcNow, ExternalIdentifier = "15K", InternalIdentifier = "CG-15K", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 14, Name = "Lancashire – H&J Commissioning Hub", Address = new Address { Line1 = "C/O NHS ENGLAND", Line2 = "1W09, 1ST FLOOR, QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", County = "WEST YORKSHIRE", Postcode = "LS2 7UE", Country = "ENGLAND" }, PrimaryRoleId = "RO98", LastUpdated = DateTime.UtcNow, ExternalIdentifier = "14X", InternalIdentifier = "CG-14X", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 12, Name = "Lancashire and Greater Manchester Commissioning Hub", Address = new Address { Line1 = "NHS ENGLAND, 1W09, 1ST FLOOR", Line2 = "QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", County = "WEST YORKSHIRE", Postcode = "LS2 7UE", Country = "ENGLAND" }, PrimaryRoleId = "RO98", LastUpdated = DateTime.UtcNow, ExternalIdentifier = "13W", InternalIdentifier = "CG-13W", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 13, Name = "Lancashire Commissioning Hub", Address = new Address { Line1 = "C/O NHS ENGLAND", Line2 = "1W09 1ST FLOOR QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", County = "WEST YORKSHIRE", Postcode = "LS2 7UE", Country = "ENGLAND" }, PrimaryRoleId = "RO98", LastUpdated = DateTime.UtcNow, ExternalIdentifier = "14K", InternalIdentifier = "CG-14K", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 16, Name = "London – H&J Commissioning Hub", Address = new Address { Line1 = "C/O NHS COMMISSIONING BOARD", Line2 = "QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", County = "WEST YORKSHIRE", Postcode = "LS2 7UE", Country = "ENGLAND" }, PrimaryRoleId = "RO98", LastUpdated = DateTime.UtcNow, ExternalIdentifier = "14M", InternalIdentifier = "CG-14M", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 15, Name = "London Commissioning Hub", Address = new Address { Line1 = "C/O NHS COMMISIONING BOARD", Line2 = "QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", County = "WEST YORKSHIRE", Postcode = "LS2 7UE", Country = "ENGLAND" }, PrimaryRoleId = "RO98", LastUpdated = DateTime.UtcNow, ExternalIdentifier = "13R", InternalIdentifier = "CG-13R", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 17, Name = "National Commissioning Hub 1", Address = new Address { Line1 = "C/O NHS ENGLAND", Line2 = "1W09, IST FLOOR, QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", County = "WEST YORKSHIRE", Postcode = "LS2 7UE", Country = "ENGLAND" }, PrimaryRoleId = "RO98", LastUpdated = DateTime.UtcNow, ExternalIdentifier = "13Q", InternalIdentifier = "CG-13Q", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 18, Name = "National Commissioning Hub 2", Address = new Address { Line1 = "C/O NHS ENGLAND", Line2 = "1W09, IST FLOOR, QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", County = "WEST YORKSHIRE", Postcode = "LS2 7UE", Country = "ENGLAND" }, PrimaryRoleId = "RO98", LastUpdated = DateTime.UtcNow, ExternalIdentifier = "15L", InternalIdentifier = "CG-15L", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 185, Name = "NHS Anglia Commissioning Support Unit", Address = new Address { Line1 = "LAKESIDE 400", Line2 = "OLD CHAPEL WAY", Line3 = "BROADLAND BUSINESS PARK", Town = "NORWICH", County = "NORFOLK", Postcode = "NR7 0WG", Country = "ENGLAND" }, PrimaryRoleId = "RO98", LastUpdated = DateTime.UtcNow, ExternalIdentifier = "0AP", InternalIdentifier = "CG-0AP", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 186, Name = "NHS Arden and Greater East Midlands Commissioning Support Unit", Address = new Address { Line1 = "ST JOHNS HOUSE", Line2 = "30 EAST STREET", Town = "LEICESTER", Postcode = "LE1 6NB", Country = "ENGLAND" }, PrimaryRoleId = "RO98", LastUpdated = DateTime.UtcNow, ExternalIdentifier = "0DE", InternalIdentifier = "CG-0DE", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 19, Name = "NHS Barking and Dagenham CCG", Address = new Address { Line1 = "6TH FLOOR", Line2 = "NORTH HOUSE", Line3 = "ST. EDWARDS WAY", Town = "ROMFORD", Postcode = "RM1 3AE", Country = "ENGLAND" }, PrimaryRoleId = "RO98", LastUpdated = DateTime.UtcNow, ExternalIdentifier = "07L", InternalIdentifier = "CG-07L", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 20, Name = "NHS Barnsley CCG", Address = new Address { Line1 = "HILLDER HOUSE", Line2 = "49-51 GAWBER ROAD", Town = "BARNSLEY", Postcode = "S75 2PY", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "02P", InternalIdentifier = "CG-02P", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 21, Name = "NHS Basildon and Brentwood CCG", Address = new Address { Line1 = "PHOENIX HOUSE", Line2 = "CHRISTOPHER MARTIN ROAD", Town = "BASILDON", Postcode = "SS14 3HG", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "99E", InternalIdentifier = "CG-99E", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 22, Name = "NHS Bassetlaw CCG", Address = new Address { Line1 = "RETFORD HOSPITAL", Line2 = "NORTH ROAD", Town = "RETFORD", County = "NOTTINGHAMSHIRE", Postcode = "DN22 7XF", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "02Q", InternalIdentifier = "CG-02Q", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 23, Name = "NHS Bath and North East Somerset, Swindon and Wiltshire CCG", Address = new Address { Line1 = "ST. MARTINS HOSPITAL", Line2 = "CLARA CROSS LANE", Town = "BATH", Postcode = "BA2 5RP", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "92G", InternalIdentifier = "CG-92G", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 24, Name = "NHS Bedfordshire CCG", Address = new Address { Line1 = "CAPABILITY HOUSE", Line2 = "WREST PARK", Line3 = "SILSOE", Town = "BEDFORD", County = "BEDFORDSHIRE", Postcode = "MK45 4HR", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "06F", InternalIdentifier = "CG-06F", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 25, Name = "NHS Berkshire West CCG", Address = new Address { Line1 = "57-59 BATH ROAD", Town = "READING", Postcode = "RG30 2BA", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "15A", InternalIdentifier = "CG-15A", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 26, Name = "NHS Birmingham and Solihull CCG", Address = new Address { Line1 = "FIRST FLOOR", Line2 = "WESLEYAN", Line3 = "COLMORE CIRCUS QUEENSWAY", Town = "BIRMINGHAM", Postcode = "B4 6AR", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "15E", InternalIdentifier = "CG-15E", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 27, Name = "NHS Birmingham Crosscity CCG", Address = new Address { Line1 = "BARTHOLOMEW HOUSE", Line2 = "142 HAGLEY ROAD", Town = "BIRMINGHAM", County = "WEST MIDLANDS", Postcode = "B16 9PA", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "13P", InternalIdentifier = "CG-13P", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 28, Name = "NHS Birmingham South and Central CCG", Address = new Address { Line1 = "BARTHOLOMEW HOUSE", Line2 = "142 HAGLEY ROAD", Town = "BIRMINGHAM", County = "WEST MIDLANDS", Postcode = "B16 9PA", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "04X", InternalIdentifier = "CG-04X", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 29, Name = "NHS Blackburn With Darwen CCG", Address = new Address { Line1 = "FUSION HOUSE", Line2 = "EVOLUTION PARK", Line3 = "HASLINGDEN ROAD", Town = "BLACKBURN", County = "LANCASHIRE", Postcode = "BB1 2FD", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "00Q", InternalIdentifier = "CG-00Q", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 30, Name = "NHS Blackpool CCG", Address = new Address { Line1 = "THE STADIUM", Line2 = "SEASIDERS WAY", Town = "BLACKPOOL", Postcode = "FY1 6JX", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "00R", InternalIdentifier = "CG-00R", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 31, Name = "NHS Bolton CCG", Address = new Address { Line1 = "ST PETERS HOUSE", Line2 = "SILVERWELL STREET", Town = "BOLTON", Postcode = "BL1 1PP", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "00T", InternalIdentifier = "CG-00T", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 32, Name = "NHS Bradford District and Craven CCG", Address = new Address { Line1 = "SCOREX HOUSE WEST", Line2 = "1 BOLTON ROAD", Town = "BRADFORD", County = "WEST YORKSHIRE", Postcode = "BD1 4AS", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "36J", InternalIdentifier = "CG-36J", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 33, Name = "NHS Brent CCG", Address = new Address { Line1 = "WEMBLEY CENTRE FOR HEALTH & CARE", Line2 = "CHAPLIN ROAD", Town = "WEMBLEY", Postcode = "HA0 4UZ", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "07P", InternalIdentifier = "CG-07P", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 34, Name = "NHS Brighton and Hove CCG", Address = new Address { Line1 = "HOVE TOWN HALL", Line2 = "NORTON ROAD", Town = "HOVE", Postcode = "BN3 4AH", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "09D", InternalIdentifier = "CG-09D", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 35, Name = "NHS Bristol CCG", Address = new Address { Line1 = "SOUTH PLAZA", Line2 = "MARLBOROUGH STREET", Town = "BRISTOL", County = "AVON", Postcode = "BS1 3NX", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "11H", InternalIdentifier = "CG-11H", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 36, Name = "NHS Bristol, North Somerset and South Gloucestershire CCG", Address = new Address { Line1 = "SOUTH PLAZA", Line2 = "MARLBOROUGH STREET", Town = "BRISTOL", Postcode = "BS1 3NX", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "15C", InternalIdentifier = "CG-15C", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 37, Name = "NHS Buckinghamshire CCG", Address = new Address { Line1 = "SECOND FLOOR", Line2 = "THE GATEWAY", Line3 = "GATEHOUSE ROAD", Town = "AYLESBURY", Postcode = "HP19 8FF", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "14Y", InternalIdentifier = "CG-14Y", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 38, Name = "NHS Bury CCG", Address = new Address { Line1 = "TOWNSIDE PRIMARY CARE CENTRE", Line2 = "1 KNOWSLEY PLACE", Line3 = "KNOWSLEY STREET", Town = "BURY", County = "LANCASHIRE", Postcode = "BL9 0SN", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "00V", InternalIdentifier = "CG-00V", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 39, Name = "NHS Calderdale CCG", Address = new Address { Line1 = "F MILL", Line2 = "DEAN CLOUGH MILLS", Town = "HALIFAX", Postcode = "HX3 5AX", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "02T", InternalIdentifier = "CG-02T", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 40, Name = "NHS Cambridgeshire and Peterborough CCG", Address = new Address { Line1 = "LOCKTON HOUSE", Line2 = "CLARENDON ROAD", Town = "CAMBRIDGE", Postcode = "CB2 8FH", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "06H", InternalIdentifier = "CG-06H", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 41, Name = "NHS Cannock Chase CCG", Address = new Address { Line1 = "BLOCK D", Line2 = "BEECROFT COURT", Line3 = "BEECROFT ROAD", Town = "CANNOCK", County = "STAFFORDSHIRE", Postcode = "WS11 1JP", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "04Y", InternalIdentifier = "CG-04Y", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 42, Name = "NHS Castle Point and Rochford CCG", Address = new Address { Line1 = "PEARL HOUSE", Line2 = "12 CASTLE ROAD", Town = "RAYLEIGH", Postcode = "SS6 7QF", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "99F", InternalIdentifier = "CG-99F", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 187, Name = "NHS Central Eastern Commissioning Support Unit", Address = new Address { Line1 = "CHARTER HOUSE", Line2 = "PARKWAY", Town = "WELWYN GARDEN CITY", County = "HERTFORDSHIRE", Postcode = "AL8 6JL", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "0CG", InternalIdentifier = "CG-0CG", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 43, Name = "NHS Central London (Westminster) CCG", Address = new Address { Line1 = "15 MARYLEBONE ROAD", Town = "LONDON", Postcode = "NW1 5JD", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "09A", InternalIdentifier = "CG-09A", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 44, Name = "NHS Central Manchester CCG", Address = new Address { Line1 = "PARKWAY ONE", Line2 = "PARKWAY BUSINESS CENTRE", Line3 = "PRINCESS ROAD", Town = "MANCHESTER", County = "GREATER MANCHESTER", Postcode = "M14 7LU", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "00W", InternalIdentifier = "CG-00W", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 188, Name = "NHS Central Midlands Commissioning Support Unit", Address = new Address { Line1 = "KINGSTON HOUSE", Line2 = "438 HIGH STREET", Town = "WEST BROMWICH", County = "WEST MIDLANDS", Postcode = "B70 9LD", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "0AD", InternalIdentifier = "CG-0AD", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 189, Name = "NHS Central Southern Commissioning Support Unit", Address = new Address { Line1 = "OXFORD ROAD", Town = "NEWBURY", County = "BERKSHIRE", Postcode = "RG14 1PA", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "0AE", InternalIdentifier = "CG-0AE", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 190, Name = "NHS Cheshire and Merseyside Commissioning Support Unit", Address = new Address { Line1 = "65 STEPHENSON WAY", Line2 = "WAVERTREE", Line3 = "TECHNOLOGY PARK", Town = "LIVERPOOL", County = "MERSEYSIDE", Postcode = "L13 1HN", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "0CE", InternalIdentifier = "CG-0CE", OrganisationType = OrganisationType.CCG },
                bobOrganisation,
                new Organisation { Id = 46, Name = "NHS Chorley and South Ribble CCG", Address = new Address { Line1 = "CHORLEY HOUSE", Line2 = "LANCASHIRE ENTERPRISE BUSINESS PARK", Line3 = "CENTURION WAY", Town = "LEYLAND", County = "LANCASHIRE", Postcode = "PR26 6TT", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "00X", InternalIdentifier = "CG-00X", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 47, Name = "NHS City and Hackney CCG", Address = new Address { Line1 = "3RD FLOOR A BLOCK", Line2 = "ST LEONARDS HOSPITAL", Line3 = "NUTTALL STREET", Town = "LONDON", County = "GREATER LONDON", Postcode = "N1 5LZ", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "07T", InternalIdentifier = "CG-07T", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 48, Name = "NHS County Durham CCG", Address = new Address { Line1 = "SALTERS LANE", Line2 = "SEDGEFIELD", Town = "STOCKTON-ON-TEES", Postcode = "TS21 3EE", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "84H", InternalIdentifier = "CG-84H", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 49, Name = "NHS Coventry and Rugby CCG", Address = new Address { Line1 = "PARKSIDE HOUSE", Line2 = "QUINTON ROAD", Town = "COVENTRY", County = "WEST MIDLANDS", Postcode = "CV1 2NJ", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "05A", InternalIdentifier = "CG-05A", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 50, Name = "NHS Derby and Derbyshire CCG", Address = new Address { Line1 = "CARDINAL SQUARE", Line2 = "10 NOTTINGHAM ROAD", Town = "DERBY", County = "DERBYSHIRE", Postcode = "DE1 3QT", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "15M", InternalIdentifier = "CG-15M", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 51, Name = "NHS Devon CCG", Address = new Address { Line1 = "COUNTY HALL", Line2 = "TOPSHAM ROAD", Town = "EXETER", County = "DEVON", Postcode = "EX2 4QL", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "15N", InternalIdentifier = "CG-15N", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 52, Name = "NHS Doncaster CCG", Address = new Address { Line1 = "SOVEREIGN HOUSE", Line2 = "HEAVENS WALK", Town = "DONCASTER", Postcode = "DN4 5HZ", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "02X", InternalIdentifier = "CG-02X", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 53, Name = "NHS Dorset CCG", Address = new Address { Line1 = "VESPASIAN HOUSE", Line2 = "BRIDPORT ROAD", Town = "DORCHESTER", County = "DORSET", Postcode = "DT1 1TG", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "11J", InternalIdentifier = "CG-11J", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 54, Name = "NHS Dudley CCG", Address = new Address { Line1 = "BRIERLEY HILL HEALTH & SOCIAL CARE", Line2 = "VENTURE WAY", Town = "BRIERLEY HILL", Postcode = "DY5 1RU", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "05C", InternalIdentifier = "CG-05C", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 55, Name = "NHS Ealing CCG", Address = new Address { Line1 = "PERCEVAL HOUSE", Line2 = "14-16 UXBRIDGE ROAD", Town = "LONDON", Postcode = "W5 2HL", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "07W", InternalIdentifier = "CG-07W", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 56, Name = "NHS East and North Hertfordshire CCG", Address = new Address { Line1 = "CHARTER HOUSE", Line2 = "PARKWAY", Town = "WELWYN GARDEN CITY", County = "HERTFORDSHIRE", Postcode = "AL8 6JL", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "06K", InternalIdentifier = "CG-06K", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 57, Name = "NHS East Berkshire CCG", Address = new Address { Line1 = "KING EDWARD VII HOSPITAL", Line2 = "ST LEONARDS ROAD", Town = "WINDSOR", Postcode = "SL4 3DP", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "15D", InternalIdentifier = "CG-15D", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 58, Name = "NHS East Lancashire CCG", Address = new Address { Line1 = "WALSHAW HOUSE", Line2 = "REGENT STREET", Town = "NELSON", Postcode = "BB9 8AS", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "01A", InternalIdentifier = "CG-01A", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 59, Name = "NHS East Leicestershire and Rutland CCG", Address = new Address { Line1 = "LEICESTERSHIRE COUNTY COUNCIL", Line2 = "ROOM 30 PEN LLOYD BUILDING", Line3 = "LEICESTER ROAD, GLENFIELD", Town = "LEICESTER", County = "LEICESTERSHIRE", Postcode = "LE3 8TB", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "03W", InternalIdentifier = "CG-03W", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 60, Name = "NHS East Riding of Yorkshire CCG", Address = new Address { Line1 = "HEALTH HOUSE", Line2 = "GRANGE PARK LANE", Line3 = "WILLERBY", Town = "HULL", Postcode = "HU10 6DT", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "02Y", InternalIdentifier = "CG-02Y", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 61, Name = "NHS East Staffordshire CCG", Address = new Address { Line1 = "EDWIN HOUSE", Line2 = "SECOND AVENUE", Line3 = "CENTRUM ONE HUNDRED", Town = "BURTON-ON-TRENT", County = "STAFFORDSHIRE", Postcode = "DE14 2WF", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "05D", InternalIdentifier = "CG-05D", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 62, Name = "NHS East Sussex CCG", Address = new Address { Line1 = "36-38 FRIARS WALK", Town = "LEWES", Postcode = "BN7 2PB", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "97R", InternalIdentifier = "CG-97R", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 63, Name = "NHS Fareham and Gosport CCG", Address = new Address { Line1 = "COMMCEN BUILDING", Line2 = "FORT SOUTHWICK", Line3 = "JAMES CALLAGHAN DRIVE", Town = "FAREHAM", Postcode = "PO17 6AR", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "10K", InternalIdentifier = "CG-10K", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 64, Name = "NHS Fylde and Wyre CCG", Address = new Address { Line1 = "DERBY ROAD", Line2 = "WESHAM", Town = "PRESTON", Postcode = "PR4 3AL", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "02M", InternalIdentifier = "CG-02M", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 65, Name = "NHS Gloucestershire CCG", Address = new Address { Line1 = "SANGER HOUSE", Line2 = "5220 VALIANT COURT", Line3 = "GLOUCESTER BUSINESS PARK, BROCKWORT", Town = "GLOUCESTER", Postcode = "GL3 4FE", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "11M", InternalIdentifier = "CG-11M", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 66, Name = "NHS Greater Huddersfield CCG", Address = new Address { Line1 = "BROAD LEA HOUSE", Line2 = "DYSON WOOD WAY", Line3 = "BRADLEY", Town = "HUDDERSFIELD", Postcode = "HD2 1GZ", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "03A", InternalIdentifier = "CG-03A", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 191, Name = "NHS Greater Manchester Commissioning Support Unit", Address = new Address { Line1 = "ST. JAMES HOUSE", Line2 = "PENDLETON WAY", Town = "SALFORD", County = "GREATER MANCHESTER", Postcode = "M6 5FW", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "0AJ", InternalIdentifier = "CG-0AJ", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 67, Name = "NHS Greater Preston CCG", Address = new Address { Line1 = "CHORLEY HOUSE", Line2 = "LANCASHIRE ENTERPRISE BUSINESS PARK", Line3 = "CENTURION WAY", Town = "LEYLAND", County = "LANCASHIRE", Postcode = "PR26 6TT", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "01E", InternalIdentifier = "CG-01E", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 68, Name = "NHS Halton CCG", Address = new Address { Line1 = "FIRST FLOOR", Line2 = "RUNCORN TOWN HALL", Line3 = "HEATH ROAD", Town = "RUNCORN", County = "CHESHIRE", Postcode = "WA7 5TD", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "01F", InternalIdentifier = "CG-01F", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 69, Name = "NHS Hammersmith and Fulham CCG", Address = new Address { Line1 = "15 MARYLEBONE ROAD", Town = "LONDON", Postcode = "NW1 5JD", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "08C", InternalIdentifier = "CG-08C", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 70, Name = "NHS Harrow CCG", Address = new Address { Line1 = "4TH FLOOR", Line2 = "THE HEIGHTS", Line3 = "59-65 LOWLANDS ROAD", Town = "HARROW", Postcode = "HA1 3AW", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "08E", InternalIdentifier = "CG-08E", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 71, Name = "NHS Havering CCG", Address = new Address { Line1 = "6TH FLOOR", Line2 = "NORTH HOUSE", Line3 = "ST EDWARDS WAY", Town = "ROMFORD", Postcode = "RM1 3AE", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "08F", InternalIdentifier = "CG-08F", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 72, Name = "NHS Herefordshire and Worcestershire CCG", Address = new Address { Line1 = "THE COACH HOUSE", Line2 = "JOHN COMYN DRIVE", Town = "WORCESTER", Postcode = "WR3 7NS", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "18C", InternalIdentifier = "CG-18C", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 73, Name = "NHS Herts Valleys CCG", Address = new Address { Line1 = "THE FORUM", Line2 = "MARLOWES", Town = "HEMEL HEMPSTEAD", Postcode = "HP1 1DN", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "06N", InternalIdentifier = "CG-06N", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 74, Name = "NHS Heywood, Middleton and Rochdale CCG", Address = new Address { Line1 = "3RD FLOOR", Line2 = "NUMBER ONE RIVERSIDE", Line3 = "SMITH STREET", Town = "ROCHDALE", Postcode = "OL16 1XU", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "01D", InternalIdentifier = "CG-01D", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 75, Name = "NHS Hillingdon CCG", Address = new Address { Line1 = "BOUNDARY HOUSE", Line2 = "CRICKET FIELD ROAD", Town = "UXBRIDGE", County = "GREATER LONDON", Postcode = "UB8 1QG", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "08G", InternalIdentifier = "CG-08G", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 76, Name = "NHS Hounslow CCG", Address = new Address { Line1 = "HOUNSLOW HOUSE", Line2 = "5TH FLOOR", Line3 = "7 BATH ROAD", Town = "HOUNSLOW", Postcode = "TW3 3EB", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "07Y", InternalIdentifier = "CG-07Y", OrganisationType = OrganisationType.CCG },
                sueOrganisation,
                new Organisation { Id = 78, Name = "NHS Ipswich and East Suffolk CCG", Address = new Address { Line1 = "ENDEAVOUR HOUSE", Line2 = "RUSSELL ROAD", Town = "IPSWICH", Postcode = "IP1 2BX", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "06L", InternalIdentifier = "CG-06L", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 79, Name = "NHS Isle of Wight CCG", Address = new Address { Line1 = "UNIT A", Line2 = "THE APEX", Line3 = "ST CROSS BUSINESS PARK", Town = "NEWPORT", Postcode = "PO30 5XW", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "10L", InternalIdentifier = "CG-10L", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 80, Name = "NHS Kent and Medway CCG", Address = new Address { Line1 = "WHARF HOUSE", Line2 = "MEDWAY WHARF ROAD", Town = "TONBRIDGE", Postcode = "TN9 1RE", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "91Q", InternalIdentifier = "CG-91Q", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 192, Name = "NHS Kent and Medway Commissioning Support Unit", Address = new Address { Line1 = "KENT HOUSE", Line2 = "81 STATION ROAD", Town = "ASHFORD", County = "KENT", Postcode = "TN23 1PP", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "0AM", InternalIdentifier = "CG-0AM", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 81, Name = "NHS Kernow CCG", Address = new Address { Line1 = "SEDGEMOOR CENTRE", Line2 = "PRIORY ROAD", Town = "ST. AUSTELL", Postcode = "PL25 5AS", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "11N", InternalIdentifier = "CG-11N", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 82, Name = "NHS Knowsley CCG", Address = new Address { Line1 = "NUTGROVE VILLA", Line2 = "WESTMORLAND ROAD", Line3 = "HUYTON", Town = "LIVERPOOL", Postcode = "L36 6GA", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "01J", InternalIdentifier = "CG-01J", OrganisationType = OrganisationType.CCG },
                aliceOrganisation,
                new Organisation { Id = 84, Name = "NHS Leeds North CCG", Address = new Address { Line1 = "LEAFIELD HOUSE", Line2 = "107-109 KING LANE", Town = "LEEDS", County = "WEST YORKSHIRE", Postcode = "LS17 5BP", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "02V", InternalIdentifier = "CG-02V", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 85, Name = "NHS Leeds West CCG", Address = new Address { Line1 = "UNITS 2-4 WIRA BUSINESS PARK", Line2 = "RING ROAD", Line3 = "WEST PARK", Town = "LEEDS", County = "WEST YORKSHIRE", Postcode = "LS16 6EB", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "03C", InternalIdentifier = "CG-03C", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 86, Name = "NHS Leicester City CCG", Address = new Address { Line1 = "ST JOHNS HOUSE", Line2 = "30 EAST STREET", Town = "LEICESTER", Postcode = "LE1 6NB", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "04C", InternalIdentifier = "CG-04C", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 87, Name = "NHS Lincolnshire CCG", Address = new Address { Line1 = "BRIDGE HOUSE", Line2 = "THE POINT", Line3 = "LIONS WAY", Town = "SLEAFORD", Postcode = "NG34 8GG", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "71E", InternalIdentifier = "CG-71E", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 88, Name = "NHS Liverpool CCG", Address = new Address { Line1 = "2 RENSHAW STREET", Town = "LIVERPOOL", Postcode = "L1 2SA", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "99A", InternalIdentifier = "CG-99A", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 89, Name = "NHS Luton CCG", Address = new Address { Line1 = "3RD FLOOR", Line2 = "ARNDALE HOUSE", Line3 = "THE MALL", Town = "LUTON", Postcode = "LU1 2LJ", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "06P", InternalIdentifier = "CG-06P", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 90, Name = "NHS Manchester CCG", Address = new Address { Line1 = "PARKWAY 3", Line2 = "PARKWAY BUSINESS CENTRE", Line3 = "PRINCESS ROAD", Town = "MANCHESTER", County = "GREATER MANCHESTER", Postcode = "M14 7LU", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "14L", InternalIdentifier = "CG-14L", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 91, Name = "NHS Mid Essex CCG", Address = new Address { Line1 = "WREN HOUSE", Line2 = "HEDGEROWS BUSINESS PARK", Line3 = "COLCHESTER ROAD", Town = "CHELMSFORD", Postcode = "CM2 5PF", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "06Q", InternalIdentifier = "CG-06Q", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 193, Name = "NHS Midlands and Lancashire Commissioning Support Unit", Address = new Address { Line1 = "KINGSTON HOUSE", Line2 = "438-450 HIGH STREET", Town = "WEST BROMWICH", Postcode = "B70 9LD", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "0CX", InternalIdentifier = "CG-0CX", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 92, Name = "NHS Milton Keynes CCG", Address = new Address { Line1 = "SHERWOOD PLACE", Line2 = "155 SHERWOOD DRIVE", Line3 = "BLETCHLEY", Town = "MILTON KEYNES", Postcode = "MK3 6RT", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "04F", InternalIdentifier = "CG-04F", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 93, Name = "NHS Morecambe Bay CCG", Address = new Address { Line1 = "MOOR LANE MILLS", Line2 = "MOOR LANE", Town = "LANCASTER", Postcode = "LA1 1QD", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "01K", InternalIdentifier = "CG-01K", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 194, Name = "NHS NEL CSU", Address = new Address { Line1 = "CLIFTON HOUSE", Line2 = "75-77 WORSHIP STREET", Town = "LONDON", Postcode = "EC2A 2DU", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "0DJ", InternalIdentifier = "CG-0DJ", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 94, Name = "NHS Newcastle Gateshead CCG", Address = new Address { Line1 = "RIVERSIDE HOUSE", Line2 = "GOLDCREST WAY", Town = "NEWCASTLE UPON TYNE", Postcode = "NE15 8NY", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "13T", InternalIdentifier = "CG-13T", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 95, Name = "NHS Newham CCG", Address = new Address { Line1 = "4TH FLOOR", Line2 = "UNEX TOWER", Line3 = "5 STATION STREET", Town = "LONDON", Postcode = "E15 1DA", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "08M", InternalIdentifier = "CG-08M", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 96, Name = "NHS Norfolk and Waveney CCG", Address = new Address { Line1 = "LAKESIDE 400", Line2 = "OLD CHAPEL WAY", Line3 = "BROADLAND BUSINESS PARK", Town = "NORWICH", Postcode = "NR7 0WG", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "26A", InternalIdentifier = "CG-26A", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 195, Name = "NHS North and East London Commissioning Support Unit", Address = new Address { Line1 = "CLIFTON HOUSE", Line2 = "75-77 WORSHIP STREET", Town = "LONDON", County = "GREATER LONDON", Postcode = "EC2A 2DU", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "0AQ", InternalIdentifier = "CG-0AQ", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 98, Name = "NHS North Central London CCG", Address = new Address { Line1 = "2ND FLOOR", Line2 = "LAYCOCK STREET", Town = "LONDON", County = "GREATER LONDON", Postcode = "N1 1TH", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "93C", InternalIdentifier = "CG-93C", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 99, Name = "NHS North Cumbria CCG", Address = new Address { Line1 = "4 WAVELL DRIVE", Line2 = "ROSEHILL INDUSTRIAL ESTATE", Town = "CARLISLE", Postcode = "CA1 2SE", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "01H", InternalIdentifier = "CG-01H", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 100, Name = "NHS North East Essex CCG", Address = new Address { Line1 = "ASPEN HOUSE", Line2 = "STEPHENSON ROAD", Line3 = "SEVERALLS BUSINESS PARK", Town = "COLCHESTER", County = "ESSEX", Postcode = "CO4 9QR", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "06T", InternalIdentifier = "CG-06T", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 101, Name = "NHS North East Hampshire and Farnham CCG", Address = new Address { Line1 = "ALDERSHOT CENTRE FOR HEALTH", Line2 = "HOSPITAL HILL", Town = "ALDERSHOT", Postcode = "GU11 1AY", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "99M", InternalIdentifier = "CG-99M", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 102, Name = "NHS North East Lincolnshire CCG", Address = new Address { Line1 = "MUNICIPAL OFFICES", Line2 = "TOWN HALL SQUARE", Town = "GRIMSBY", Postcode = "DN31 1HU", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "03H", InternalIdentifier = "CG-03H", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 104, Name = "NHS North Hampshire CCG", Address = new Address { Line1 = "CENTRAL 40 LIME TREE WAY", Line2 = "CROCKFORD LANE", Line3 = "CHINEHAM BUSINESS PARK, CHINEHAM", Town = "BASINGSTOKE", County = "HAMPSHIRE", Postcode = "RG24 8GU", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "10J", InternalIdentifier = "CG-10J", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 105, Name = "NHS North Kirklees CCG", Address = new Address { Line1 = "4TH FLOOR", Line2 = "EMPIRE HOUSE", Line3 = "WAKEFIELD ROAD", Town = "DEWSBURY", County = "WEST YORKSHIRE", Postcode = "WF12 8DJ", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "03J", InternalIdentifier = "CG-03J", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 106, Name = "NHS North Lincolnshire CCG", Address = new Address { Line1 = "THE HEALTH PLACE", Line2 = "WRAWBY ROAD", Town = "BRIGG", Postcode = "DN20 8GS", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "03K", InternalIdentifier = "CG-03K", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 196, Name = "NHS North of England Commissioning Support Unit", Address = new Address { Line1 = "JOHN SNOW HOUSE", Line2 = "DURHAM UNIVERSITY SCIENCE PARK", Town = "DURHAM", Postcode = "DH1 3YG", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "0AR", InternalIdentifier = "CG-0AR", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 107, Name = "NHS North Staffordshire CCG", Address = new Address { Line1 = "MORSTON HOUSE", Line2 = "THE MIDWAY", Town = "NEWCASTLE", County = "STAFFORDSHIRE", Postcode = "ST5 1QG", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "05G", InternalIdentifier = "CG-05G", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 108, Name = "NHS North Tyneside CCG", Address = new Address { Line1 = "12 HEDLEY COURT", Line2 = "ORION BUSINESS PARK", Town = "NORTH SHIELDS", Postcode = "NE29 7ST", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "99C", InternalIdentifier = "CG-99C", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 197, Name = "NHS North West London Commissioning Support Unit", Address = new Address { Line1 = "15 MARYLEBONE ROAD", Town = "LONDON", County = "GREATER LONDON", Postcode = "NW1 5JD", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "0AT", InternalIdentifier = "CG-0AT", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 110, Name = "NHS North Yorkshire CCG", Address = new Address { Line1 = "1 GRIMBALD CRAG COURT", Town = "KNARESBOROUGH", Postcode = "HG5 8QB", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "42D", InternalIdentifier = "CG-42D", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 97, Name = "NHS Northamptonshire CCG", Address = new Address { Line1 = "FRANCIS CRICK HOUSE", Line2 = "6 SUMMERHOUSE ROAD", Line3 = "MOULTON PARK INDUSTRIAL ESTATE", Town = "NORTHAMPTON", County = "NORTHAMPTONSHIRE", Postcode = "NN3 6BF", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "78H", InternalIdentifier = "CG-78H", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 103, Name = "NHS Northern, Eastern and Western Devon CCG", Address = new Address { Line1 = "NEWCOURT HOUSE", Line2 = "OLD RYDON LANE", Town = "EXETER", County = "DEVON", Postcode = "EX2 7JU", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "99P", InternalIdentifier = "CG-99P", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 109, Name = "NHS Northumberland CCG", Address = new Address { Line1 = "COUNTY HALL", Town = "MORPETH", Postcode = "NE61 2EF", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "00L", InternalIdentifier = "CG-00L", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 111, Name = "NHS Nottingham and Nottinghamshire CCG", Address = new Address { Line1 = "BIRCH HOUSE", Line2 = "RANSOM WOOD BUSINESS PARK", Line3 = "SOUTHWELL ROAD WEST", Town = "MANSFIELD", Postcode = "NG21 0HJ", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "52R", InternalIdentifier = "CG-52R", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 112, Name = "NHS Oldham CCG", Address = new Address { Line1 = "ELLEN HOUSE", Line2 = "WADDINGTON STREET", Town = "OLDHAM", Postcode = "OL9 6EE", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "00Y", InternalIdentifier = "CG-00Y", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 113, Name = "NHS Oxfordshire CCG", Address = new Address { Line1 = "JUBILEE HOUSE", Line2 = "5510 JOHN SMITH DRIVE", Line3 = "OXFORD BUSINESS PARK SOUTH", Town = "OXFORD", Postcode = "OX4 2LH", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "10Q", InternalIdentifier = "CG-10Q", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 114, Name = "NHS Portsmouth CCG", Address = new Address { Line1 = "4TH FLOOR", Line2 = "1 GUILDHALL SQUARE", Town = "PORTSMOUTH", County = "HAMPSHIRE", Postcode = "PO1 2GJ", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "10R", InternalIdentifier = "CG-10R", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 115, Name = "NHS Redbridge CCG", Address = new Address { Line1 = "6TH FLOOR", Line2 = "NORTH HOUSE", Line3 = "ST EDWARDS WAY", Town = "ROMFORD", Postcode = "RM1 3AE", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "08N", InternalIdentifier = "CG-08N", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 116, Name = "NHS Rotherham CCG", Address = new Address { Line1 = "OAK HOUSE", Line2 = "MOORHEAD WAY", Line3 = "BRAMLEY", Town = "ROTHERHAM", Postcode = "S66 1YY", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "03L", InternalIdentifier = "CG-03L", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 117, Name = "NHS Salford CCG", Address = new Address { Line1 = "ST JAMES HOUSE - 7TH FLOOR", Line2 = "PENDLETON WAY", Town = "SALFORD", Postcode = "M6 5FW", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "01G", InternalIdentifier = "CG-01G", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 118, Name = "NHS Sandwell and West Birmingham CCG", Address = new Address { Line1 = "KINGSTON HOUSE", Line2 = "438-450 HIGH STREET", Town = "WEST BROMWICH", Postcode = "B70 9LD", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "05L", InternalIdentifier = "CG-05L", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 119, Name = "NHS Sheffield CCG", Address = new Address { Line1 = "722 PRINCE OF WALES ROAD", Line2 = "DARNALL", Town = "SHEFFIELD", Postcode = "S9 4EU", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "03N", InternalIdentifier = "CG-03N", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 120, Name = "NHS Shropshire CCG", Address = new Address { Line1 = "WILLIAM FARR HOUSE", Line2 = "MYTTON OAK ROAD", Town = "SHREWSBURY", County = "SHROPSHIRE", Postcode = "SY3 8XL", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "05N", InternalIdentifier = "CG-05N", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 121, Name = "NHS Solihull CCG", Address = new Address { Line1 = "FRIARS GATE", Line2 = "1011 STRATFORD ROAD", Line3 = "SHIRLEY", Town = "SOLIHULL", County = "WEST MIDLANDS", Postcode = "B90 4BN", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "05P", InternalIdentifier = "CG-05P", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 122, Name = "NHS Somerset CCG", Address = new Address { Line1 = "WYNFORD HOUSE", Line2 = "LUFTON WAY", Line3 = "LUFTON", Town = "YEOVIL", Postcode = "BA22 8HR", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "11X", InternalIdentifier = "CG-11X", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 124, Name = "NHS South Devon and Torbay CCG", Address = new Address { Line1 = "POMONA HOUSE", Line2 = "OAK VIEW CLOSE", Town = "TORQUAY", County = "DEVON", Postcode = "TQ2 7FF", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "99Q", InternalIdentifier = "CG-99Q", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 126, Name = "NHS South East London CCG", Address = new Address { Line1 = "160 TOOLEY STREET", Town = "LONDON", Postcode = "SE1 2TZ", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "72Q", InternalIdentifier = "CG-72Q", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 127, Name = "NHS South East Staffordshire and Seisdon Peninsula CCG", Address = new Address { Line1 = "MERLIN HOUSE", Line2 = "BITTERSCOTE", Line3 = "ETCHELL ROAD", Town = "TAMWORTH", County = "STAFFORDSHIRE", Postcode = "B78 3HF", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "05Q", InternalIdentifier = "CG-05Q", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 125, Name = "NHS South Eastern Hampshire CCG", Address = new Address { Line1 = "COMMCEN BUILDING", Line2 = "FORT SOUTHWICK", Line3 = "JAMES CALLAGHAN DRIVE", Town = "FAREHAM", Postcode = "PO17 6AR", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "10V", InternalIdentifier = "CG-10V", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 129, Name = "NHS South Gloucestershire CCG", Address = new Address { Line1 = "CORUM 2, CORUM OFFICE PARK", Line2 = "CROWN WAY", Line3 = "WARMLEY", Town = "BRISTOL", County = "AVON", Postcode = "BS30 8FJ", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "12A", InternalIdentifier = "CG-12A", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 199, Name = "NHS South London Commissioning Support Unit", Address = new Address { Line1 = "1 LOWER MARSH", Town = "LONDON", County = "GREATER LONDON", Postcode = "SE1 7NT", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "0AX", InternalIdentifier = "CG-0AX", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 131, Name = "NHS South Sefton CCG", Address = new Address { Line1 = "3RD FLOOR", Line2 = "MERTON HOUSE", Line3 = "STANLEY ROAD", Town = "BOOTLE", Postcode = "L20 3DL", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "01T", InternalIdentifier = "CG-01T", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 132, Name = "NHS South Tyneside CCG", Address = new Address { Line1 = "MONKTON HALL", Line2 = "MONKTON LANE", Line3 = "MONKTON VILLAGE", Town = "JARROW", Postcode = "NE32 5NN", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "00N", InternalIdentifier = "CG-00N", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 133, Name = "NHS South Warwickshire CCG", Address = new Address { Line1 = "WESTGATE HOUSE", Line2 = "21 MARKET STREET", Town = "WARWICK", County = "WARWICKSHIRE", Postcode = "CV34 4DE", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "05R", InternalIdentifier = "CG-05R", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 134, Name = "NHS South West London CCG", Address = new Address { Line1 = "120 THE BROADWAY", Town = "LONDON", County = "GREATER LONDON", Postcode = "SW19 1RH", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "36L", InternalIdentifier = "CG-36L", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 198, Name = "NHS South, Central and West Commissioning Support Unit", Address = new Address { Line1 = "OMEGA HOUSE", Line2 = "112 SOUTHAMPTON ROAD", Town = "EASTLEIGH", Postcode = "SO50 5PB", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "0DF", InternalIdentifier = "CG-0DF", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 123, Name = "NHS Southampton CCG", Address = new Address { Line1 = "OAKLEY ROAD", Town = "SOUTHAMPTON", Postcode = "SO16 4GX", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "10X", InternalIdentifier = "CG-10X", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 128, Name = "NHS Southend CCG", Address = new Address { Line1 = "FLOOR 6", Line2 = "CIVIC CENTRE", Line3 = "VICTORIA AVENUE", Town = "SOUTHEND-ON-SEA", County = "ESSEX", Postcode = "SS2 6EN", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "99G", InternalIdentifier = "CG-99G", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 130, Name = "NHS Southport and Formby CCG", Address = new Address { Line1 = "5 CURZON ROAD", Town = "SOUTHPORT", County = "MERSEYSIDE", Postcode = "PR8 6PL", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "01V", InternalIdentifier = "CG-01V", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 136, Name = "NHS St Helens CCG", Address = new Address { Line1 = "ST HELENS CHAMBER OF COMMERCE", Line2 = "SALISBURY STREET", Line3 = "CHALON WAY", Town = "ST. HELENS", County = "MERSEYSIDE", Postcode = "WA10 1FY", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "01X", InternalIdentifier = "CG-01X", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 135, Name = "NHS Stafford and Surrounds CCG", Address = new Address { Line1 = "STAFFORDSHIRE PLACE 2", Town = "STAFFORD", County = "STAFFORDSHIRE", Postcode = "ST16 2LP", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "05V", InternalIdentifier = "CG-05V", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 200, Name = "NHS Staffordshire and Lancashire Commissioning Support Unit", Address = new Address { Line1 = "ANGLESEY HOUSE", Line2 = "TOWERS BUSINESS PARK", Line3 = "WHEELHOUSE ROAD", Town = "RUGELEY", County = "STAFFORDSHIRE", Postcode = "WS15 1UZ", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "0CH", InternalIdentifier = "CG-0CH", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 137, Name = "NHS Stockport CCG", Address = new Address { Line1 = "4TH FLOOR", Line2 = "STOPFORD HOUSE", Town = "STOCKPORT", County = "CHESHIRE", Postcode = "SK1 3XE", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "01W", InternalIdentifier = "CG-01W", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 138, Name = "NHS Stoke On Trent CCG", Address = new Address { Line1 = "HERBERT MINTON BUILDING", Line2 = "79 LONDON ROAD", Town = "STOKE-ON-TRENT", County = "STAFFORDSHIRE", Postcode = "ST4 7PZ", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "05W", InternalIdentifier = "CG-05W", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 139, Name = "NHS Sunderland CCG", Address = new Address { Line1 = "PEMBERTON HOUSE", Line2 = "COLIMA AVENUE", Line3 = "SUNDERLAND ENTERPRISE PARK", Town = "SUNDERLAND", Postcode = "SR5 3XB", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "00P", InternalIdentifier = "CG-00P", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 201, Name = "NHS Surrey and Sussex Commissioning Support Unit", Address = new Address { Line1 = "36-38 FRIARS WALK", Town = "LEWES", County = "EAST SUSSEX", Postcode = "BN7 2PB", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "0CC", InternalIdentifier = "CG-0CC", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 140, Name = "NHS Surrey Heartlands CCG", Address = new Address { Line1 = "CEDAR COURT", Line2 = "GUILDFORD ROAD", Line3 = "FETCHAM", Town = "LEATHERHEAD", Postcode = "KT22 9AE", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "92A", InternalIdentifier = "CG-92A", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 141, Name = "NHS Surrey Heath CCG", Address = new Address { Line1 = "SURREY HEATH HOUSE", Line2 = "KNOLL ROAD", Town = "CAMBERLEY", County = "SURREY", Postcode = "GU15 3HD", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "10C", InternalIdentifier = "CG-10C", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 142, Name = "NHS Tameside and Glossop CCG", Address = new Address { Line1 = "TAMESIDE ONE", Line2 = "MARKET PLACE", Town = "ASHTON-UNDER-LYNE", County = "GREATER MANCHESTER", Postcode = "OL6 6BH", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "01Y", InternalIdentifier = "CG-01Y", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 143, Name = "NHS Tees Valley CCG", Address = new Address { Line1 = "NORTH ORMESBY HEALTH VILLAGE", Line2 = "FIRST FLOOR, 14 TRINITY MEWS", Line3 = "NORTH ORMESBY", Town = "MIDDLESBROUGH", County = "NORTH YORKSHIRE", Postcode = "TS3 6AL", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "16C", InternalIdentifier = "CG-16C", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 144, Name = "NHS Telford and Wrekin CCG", Address = new Address { Line1 = "HALESFIELD 6", Line2 = "EPIC PARK", Town = "TELFORD", County = "SHROPSHIRE", Postcode = "TF7 4BF", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "05X", InternalIdentifier = "CG-05X", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 145, Name = "NHS Thurrock CCG", Address = new Address { Line1 = "CIVIC OFFICES", Line2 = "NEW ROAD", Town = "GRAYS", County = "ESSEX", Postcode = "RM17 6SL", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "07G", InternalIdentifier = "CG-07G", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 146, Name = "NHS Tower Hamlets CCG", Address = new Address { Line1 = "2ND FLOOR ALDERNEY BUILDING", Line2 = "MILE END HOSPITAL", Line3 = "BANCROFT ROAD", Town = "LONDON", Postcode = "E1 4DG", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "08V", InternalIdentifier = "CG-08V", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 147, Name = "NHS Trafford CCG", Address = new Address { Line1 = "1ST FLOOR TRAFFORD TOWN HALL", Line2 = "TALBOT ROAD", Line3 = "STRETFORD", Town = "MANCHESTER", Postcode = "M32 0TH", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "02A", InternalIdentifier = "CG-02A", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 148, Name = "NHS Vale of York CCG", Address = new Address { Line1 = "WEST OFFICES", Line2 = "STATION RISE", Town = "YORK", County = "NORTH YORKSHIRE", Postcode = "YO1 6GA", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "03Q", InternalIdentifier = "CG-03Q", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 149, Name = "NHS Wakefield CCG", Address = new Address { Line1 = "WHITE ROSE HOUSE", Line2 = "WEST PARADE", Town = "WAKEFIELD", Postcode = "WF1 1LT", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "03R", InternalIdentifier = "CG-03R", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 150, Name = "NHS Walsall CCG", Address = new Address { Line1 = "JUBILEE HOUSE", Line2 = "BLOXWICH LANE", Town = "WALSALL", Postcode = "WS2 7JL", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "05Y", InternalIdentifier = "CG-05Y", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 151, Name = "NHS Waltham Forest CCG", Address = new Address { Line1 = "KIRKDALE HOUSE", Line2 = "7 KIRKDALE ROAD", Town = "LONDON", Postcode = "E11 1HP", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "08W", InternalIdentifier = "CG-08W", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 152, Name = "NHS Warrington CCG", Address = new Address { Line1 = "110 BIRCHWOOD BOULEVARD", Line2 = "BIRCHWOOD", Town = "WARRINGTON", County = "CHESHIRE", Postcode = "WA3 7QH", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "02E", InternalIdentifier = "CG-02E", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 153, Name = "NHS Warwickshire North CCG", Address = new Address { Line1 = "WESTGATE HOUSE", Line2 = "21 MARKET STREET", Town = "WARWICK", County = "WARWICKSHIRE", Postcode = "CV34 4DE", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "05H", InternalIdentifier = "CG-05H", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 202, Name = "NHS West and South Yorkshire and Bassetlaw Commissioning Support Unit", Address = new Address { Line1 = "DOUGLAS MILLS", Line2 = "BOWLING OLD LANE", Town = "BRADFORD", County = "WEST YORKSHIRE", Postcode = "BD5 7JR", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "0CF", InternalIdentifier = "CG-0CF", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 154, Name = "NHS West Essex CCG", Address = new Address { Line1 = "BUILDING 4, SPENCER CLOSE", Line2 = "ST MARGARET'S HOSPITAL", Line3 = "THE PLAIN", Town = "EPPING", Postcode = "CM16 6TN", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "07H", InternalIdentifier = "CG-07H", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 155, Name = "NHS West Hampshire CCG", Address = new Address { Line1 = "OMEGA HOUSE", Line2 = "112 SOUTHAMPTON ROAD", Town = "EASTLEIGH", Postcode = "SO50 5PB", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "11A", InternalIdentifier = "CG-11A", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 156, Name = "NHS West Lancashire CCG", Address = new Address { Line1 = "HILLDALE", Line2 = "WIGAN ROAD", Town = "ORMSKIRK", Postcode = "L39 2JW", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "02G", InternalIdentifier = "CG-02G", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 157, Name = "NHS West Leicestershire CCG", Address = new Address { Line1 = "55 WOODGATE", Town = "LOUGHBOROUGH", Postcode = "LE11 2TZ", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "04V", InternalIdentifier = "CG-04V", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 158, Name = "NHS West London CCG", Address = new Address { Line1 = "15 MARYLEBONE ROAD", Town = "LONDON", Postcode = "NW1 5JD", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "08Y", InternalIdentifier = "CG-08Y", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 159, Name = "NHS West Suffolk CCG", Address = new Address { Line1 = "WEST SUFFOLK HOUSE", Line2 = "WESTERN WAY", Town = "BURY ST. EDMUNDS", County = "SUFFOLK", Postcode = "IP33 3YU", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "07K", InternalIdentifier = "CG-07K", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 160, Name = "NHS West Sussex CCG", Address = new Address { Line1 = "WICKER HOUSE", Line2 = "HIGH STREET", Town = "WORTHING", Postcode = "BN11 1DJ", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "70F", InternalIdentifier = "CG-70F", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 161, Name = "NHS Wigan Borough CCG", Address = new Address { Line1 = "WIGAN LIFE CENTRE", Line2 = "COLLEGE AVENUE", Town = "WIGAN", Postcode = "WN1 1NJ", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "02H", InternalIdentifier = "CG-02H", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 162, Name = "NHS Windsor, Ascot and Maidenhead CCG", Address = new Address { Line1 = "KING EDWARD VII HOSPITAL", Line2 = "ST LEONARD ROAD", Town = "WINDSOR", County = "BERKSHIRE", Postcode = "SL4 3DP", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "11C", InternalIdentifier = "CG-11C", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 163, Name = "NHS Wirral CCG", Address = new Address { Line1 = "OLD MARKET HOUSE", Line2 = "13 HAMILTON STREET", Town = "BIRKENHEAD", Postcode = "CH41 5AL", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "12F", InternalIdentifier = "CG-12F", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 164, Name = "NHS Wokingham CCG", Address = new Address { Line1 = "CHALFONT SURGERY", Line2 = "CHALFONT CLOSE", Line3 = "EARLEY", Town = "READING", County = "BERKSHIRE", Postcode = "RG6 5HZ", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "11D", InternalIdentifier = "CG-11D", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 165, Name = "NHS Wolverhampton CCG", Address = new Address { Line1 = "TECHNOLOGY CENTRE", Line2 = "GLAISHER DRIVE", Line3 = "WOLVERHAMPTON SCIENCE PARK", Town = "WOLVERHAMPTON", County = "WEST MIDLANDS", Postcode = "WV10 9RU", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "06A", InternalIdentifier = "CG-06A", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 167, Name = "North East and Yorkshire – H&J Commissioning Hub", Address = new Address { Line1 = "C/O NHS ENGLAND", Line2 = "1W09, 1ST FLOOR, QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", Postcode = "LS2 7UA", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "76A", InternalIdentifier = "CG-76A", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 166, Name = "North East and Yorkshire Commissioning Hub", Address = new Address { Line1 = "C/O NHS ENGLAND", Line2 = "1W09, 1ST FLOOR, QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", Postcode = "LS2 7UA", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "85J", InternalIdentifier = "CG-85J", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 169, Name = "North Midlands – H&J Commissioning Hub", Address = new Address { Line1 = "C/O NHS ENGLAND", Line2 = "1W09, FIRST FLOOR, QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", County = "WEST YORKSHIRE", Postcode = "LS2 7UE", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "14Q", InternalIdentifier = "CG-14Q", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 168, Name = "North Midlands Commissioning Hub", Address = new Address { Line1 = "C/O NHS ENGLAND, 1W09, 1ST FLOOR", Line2 = "QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", County = "WEST YORKSHIRE", Postcode = "LS2 7UE", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "14A", InternalIdentifier = "CG-14A", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 171, Name = "North West – H&J Commissioning Hub", Address = new Address { Line1 = "C/O NHS ENGLAND", Line2 = "1W09, 1ST FLOOR, QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", Postcode = "LS2 7UA", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "32T", InternalIdentifier = "CG-32T", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 170, Name = "North West Commissioning Hub", Address = new Address { Line1 = "C/O NHS ENGLAND", Line2 = "1W09, 1ST FLOOR, QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", Postcode = "LS2 7UA", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "27T", InternalIdentifier = "CG-27T", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 203, Name = "Optum Health Solutions (UK) Limited", Address = new Address { Line1 = "1ST FLOOR STAR HOUSE", Line2 = "20 GRENFELL ROAD", Town = "MAIDENHEAD", County = "BERKSHIRE", Postcode = "SL6 1EH", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "0DG", InternalIdentifier = "CG-0DG", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 172, Name = "South Central Commissioning Hub", Address = new Address { Line1 = "C/O NHS ENGLAND, 1W09, 1ST FLOOR", Line2 = "QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", County = "WEST YORKSHIRE", Postcode = "LS2 7UE", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "14H", InternalIdentifier = "CG-14H", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 174, Name = "South East – H&J Commissioning Hub", Address = new Address { Line1 = "C/O NHS ENGLAND", Line2 = "1W09, 1ST FLOOR, QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", Postcode = "LS2 7UA", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "97T", InternalIdentifier = "CG-97T", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 173, Name = "South East Commissioning Hub", Address = new Address { Line1 = "C/O NHS ENGLAND, 1W09, 1ST FLOOR", Line2 = "QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", County = "WEST YORKSHIRE", Postcode = "LS2 7UE", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "14G", InternalIdentifier = "CG-14G", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 175, Name = "South West Commissioning Hub", Address = new Address { Line1 = "C/O NHS ENGLAND, 1W09, 1ST FLOOR", Line2 = "QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", County = "WEST YORKSHIRE", Postcode = "LS2 7UE", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "14F", InternalIdentifier = "CG-14F", OrganisationType = OrganisationType.CCG },
                daveOrganisation,
                new Organisation { Id = 178, Name = "South West South – H&J Commissioning Hub", Address = new Address { Line1 = "C/O NHS ENGLAND", Line2 = "1W09, 1ST FLOOR, QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", County = "WEST YORKSHIRE", Postcode = "LS2 7UE", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "14T", InternalIdentifier = "CG-14T", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 177, Name = "South West South Commissioning Hub", Address = new Address { Line1 = "NHS ENGLAND", Line2 = "QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", County = "WEST YORKSHIRE", Postcode = "LS2 7UE", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "15G", InternalIdentifier = "CG-15G", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 179, Name = "Wessex Commissioning Hub", Address = new Address { Line1 = "C/O NHS ENGLAND", Line2 = "1W09, 1ST FLOOR, QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", County = "WEST YORKSHIRE", Postcode = "LS2 7UE", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "13N", InternalIdentifier = "CG-13N", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 180, Name = "West Midlands Commissioning Hub", Address = new Address { Line1 = "C/O NHS ENGLAND, 1W09, 1ST FLOOR", Line2 = "QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", County = "WEST YORKSHIRE", Postcode = "LS2 7UE", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "14C", InternalIdentifier = "CG-14C", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 182, Name = "Yorkshire and Humber – H&J Commissioning Hub", Address = new Address { Line1 = "C/O NHS ENGLAND", Line2 = "1W09, 1ST FLOOR, QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", County = "WEST YORKSHIRE", Postcode = "LS2 7UE", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "14N", InternalIdentifier = "CG-14N", OrganisationType = OrganisationType.CCG },
                new Organisation { Id = 181, Name = "Yorkshire and Humber Commissioning Hub", Address = new Address { Line1 = "C/O NHS ENGLAND, 1W09, 1ST FLOOR", Line2 = "QUARRY HOUSE", Line3 = "QUARRY HILL", Town = "LEEDS", County = "WEST YORKSHIRE", Postcode = "LS2 7UE", Country = "ENGLAND" }, PrimaryRoleId = "RO98",  LastUpdated = DateTime.UtcNow, ExternalIdentifier = "13V", InternalIdentifier = "CG-13V", OrganisationType = OrganisationType.CCG },
            };

            context.InsertRangeWithIdentity(organisations);

            // Users
            var adminUser = new AspNetUser
            {
                Id = BobId,
                Email = "BobSmith@email.com",
                NormalizedEmail = "BOBSMITH@EMAIL.COM",
                UserName = "BobSmith@email.com",
                NormalizedUserName = "BOBSMITH@EMAIL.COM",
                Disabled = false,
                FirstName = "Bob",
                LastName = "Smith",
                EmailConfirmed = true,
                CatalogueAgreementSigned = true,
                PrimaryOrganisation = bobOrganisation,
                PrimaryOrganisationId = bobOrganisation.Id,
                SecurityStamp = Guid.NewGuid().ToString(),
                HasOptedInUserResearch = false,
                AcceptedTermsOfUseDate = DateTime.UtcNow,
            };
            adminUser.AspNetUserRoles.Add(new AspNetUserRole() { Role = adminRole });
            adminUser.PasswordHash = new PasswordHasher<AspNetUser>().HashPassword(adminUser, TestPassword);

            var buyUser = new AspNetUser
            {
                Id = SueId,
                Email = "SueSmith@email.com",
                NormalizedEmail = "SUESMITH@EMAIL.COM",
                UserName = "SueSmith@email.com",
                NormalizedUserName = "SUESMITH@EMAIL.COM",
                Disabled = false,
                FirstName = "Sue",
                LastName = "Smith",
                EmailConfirmed = true,
                CatalogueAgreementSigned = true,
                PrimaryOrganisation = sueOrganisation,
                PrimaryOrganisationId = sueOrganisation.Id,
                SecurityStamp = Guid.NewGuid().ToString(),
                HasOptedInUserResearch = false,
                AcceptedTermsOfUseDate = DateTime.UtcNow,
            };
            buyUser.AspNetUserRoles.Add(new AspNetUserRole() { Role = buyerRole });
            buyUser.PasswordHash = new PasswordHasher<AspNetUser>().HashPassword(buyUser, TestPassword);

            var buyProxyUser = new AspNetUser
            {
                Id = AliceId,
                Email = AliceEmail,
                NormalizedEmail = AliceEmail.ToUpperInvariant(),
                UserName = AliceEmail,
                NormalizedUserName = AliceEmail.ToUpperInvariant(),
                Disabled = false,
                FirstName = "Alice",
                LastName = "Smith",
                EmailConfirmed = true,
                CatalogueAgreementSigned = true,
                PrimaryOrganisation = aliceOrganisation,
                PrimaryOrganisationId = aliceOrganisation.Id,
                SecurityStamp = Guid.NewGuid().ToString(),
                HasOptedInUserResearch = true,
                AcceptedTermsOfUseDate = DateTime.UtcNow,
            };
            buyProxyUser.AspNetUserRoles.Add(new AspNetUserRole() { Role = buyerRole });
            buyProxyUser.PasswordHash = new PasswordHasher<AspNetUser>().HashPassword(buyProxyUser, TestPassword);

            var accountManagerUser = new AspNetUser
            {
                Id = DaveId,
                Email = DaveEmail,
                NormalizedEmail = DaveEmail.ToUpperInvariant(),
                UserName = DaveEmail,
                NormalizedUserName = DaveEmail.ToUpperInvariant(),
                Disabled = false,
                FirstName = "Dave",
                LastName = "Smith",
                EmailConfirmed = true,
                CatalogueAgreementSigned = true,
                PrimaryOrganisation = daveOrganisation,
                PrimaryOrganisationId = daveOrganisation.Id,
                SecurityStamp = Guid.NewGuid().ToString(),
                HasOptedInUserResearch = false,
                AcceptedTermsOfUseDate = DateTime.UtcNow,
            };
            accountManagerUser.AspNetUserRoles.Add(new AspNetUserRole() { Role = accountManagerRole });
            accountManagerUser.PasswordHash = new PasswordHasher<AspNetUser>().HashPassword(accountManagerUser, TestPassword);

            var users = new[] { adminUser, buyUser, buyProxyUser, accountManagerUser };

            context.InsertRangeWithIdentity(users);
        }
    }
}
